### DISCUSSION TITLE
wheels accumulate libs from different versions

### DISCUSSION THREAD

**Discussion by nschloe** [pypa/cibuildwheel#1048] [Q&A]
I'm using cibuildwheels on gh-actions to compile my Python code into wheels. This is my config:
```yaml
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_BUILD: cp37-* cp38-* cp39-* cp310-*
          CIBW_SKIP: "*-musllinux*"
          CIBW_ARCHS: native
```
This produces the output files

```
foobar-1.0.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
foobar-1.0.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
foobar-1.0.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
foobar-1.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```
I noticed that 
- the cp37-wheel contains the cp37 lib,
- the cp38-wheel contains the cp38 lib _and_ the cp37 lib,
- the cp39-wheel contains the cp39 lib _and_ the cp38 lib _and_ the cp37 lib,
- the cp310-wheel contains the cp310 lib _and_ cp39 lib _and_ the cp38 lib _and_ the cp37 lib.

Any idea what's going wrong here?
