### DISCUSSION TITLE
issues with cross-platform builds for Apple Silicon (M1/M2)

### DISCUSSION THREAD

**Discussion by nschloe** [pypa/cibuildwheel#1150] [Q&A] [answered]
I'm having issues with compiling for Apple Silicon using cibuildwheel 2.7.0 (and all earlier versions I have tried). My GitHub action config is
```yaml
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.7.0
        env:
          CIBW_BUILD: cp37-* cp38-* cp39-* cp310-*
          CIBW_BEFORE_BUILD: rm -rf build/
          CIBW_ARCHS_WIN: auto
          CIBW_ARCHS_MACOS: x86_64 arm64
          # CIBW_ARCHS_MACOS: x86_64 universal2  # same issues
          CIBW_ARCHS_LINUX: auto
```
The build seems to work fine:
```
_ _       _ _   _       _           _
 ___|_| |_ _ _|_| |_| |_ _ _| |_ ___ ___| |
|  _| | . | | | | | . | | | |   | -_| -_| |
|___|_|___|___|_|_|___|_____|_|_|___|___|_|
cibuildwheel version 2.7.0
Build options:
  platform: 'macos'
  architectures: {<Architecture.arm64: 'arm64'>, <Architecture.x86_64: 'x86_64'>}
  build_selector: BuildSelector(build_config='cp37-* cp38-* cp39-* cp[31](https://github.com/foo/bar/runs/6954461923?check_suite_focus=true#step:5:33)0-*', skip_config='', requires_python=<SpecifierSet('>=3.7')>, prerelease_pythons=False)
  output_dir: PosixPath('/Users/runner/work/bar/bar/wheelhouse')
  package_dir: PosixPath('/Users/runner/work/bar/bar')
  test_selector: TestSelector(skip_config='')
  before_all: ''
  before_build: 'rm -rf build/'
  before_test: ''
  build_frontend: 'pip'
  build_verbosity: 0
  dependency_constraints: DependencyConstraints(PosixPath('/usr/local/Cellar/pipx/1.1.0/.cache/[42](https://github.com/foo/bar/runs/6954461923?check_suite_focus=true#step:5:44)a98e1d0b0a0f6/lib/python3.10/site-packages/cibuildwheel/resources/constraints.txt'))
  environment: ParsedEnvironment([])
  manylinux_images: None
  musllinux_images: None
  repair_command: 'delocate-listdeps {wheel} && delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}'
  test_command: ''
  test_extras: ''
  test_requires: []
Cache folder: /Users/runner/Library/Caches/cibuildwheel
```
and produce
```
  bar-0.0.1-cp310-cp310-macosx_10_9_x86_64.whl   254 kB
  bar-0.0.1-cp310-cp310-macosx_11_0_arm64.whl    254 kB
  bar-0.0.1-cp37-cp37m-macosx_10_9_x86_64.whl    238 kB
  bar-0.0.1-cp38-cp38-macosx_10_9_x86_64.whl     258 kB
  bar-0.0.1-cp38-cp38-macosx_11_0_arm64.whl      258 kB
  bar-0.0.1-cp39-cp39-macosx_10_9_x86_64.whl     250 kB
  bar-0.0.1-cp39-cp39-macosx_11_0_arm64.whl      250 kB
```
However, when installing and using a package, M1/M2 users report the following error:
```
File "/opt/homebrew/bin/foo", line 5, in <module>
    from foo.cli import main
  File "/opt/homebrew/lib/python3.9/site-packages/foo/__init__.py", line 1, in <module>
    from bar import __fun__
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/[bar.cpython-39-darwin.so](http://bar.cpython-39-darwin.so/), 0x0002): tried: '/opt/homebrew/lib/python3.9/site-packages/[bar.cpython-39-darwin.so](http://bar.cpython-39-darwin.so/)'
(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```
Any idea what's going wrong here?
