### DISCUSSION TITLE
Dynamically generating GitHub Actions matrix to avoid timeouts when emulating architectures

### DISCUSSION THREAD

**Discussion by mwilliamson** [pypa/cibuildwheel#1261] [Show and tell]
Hello! I maintain some Python bindings for jq, and use cibuildwheel to build its binary wheels. When trying to make a release recently, I ran into trouble since building the aarch64 wheels took more than six hours due to the slowness of the emulation.

To get around this, it seemed like the best approach would be to have multiple GitHub Actions jobs running in parallel, rather than one for each architecture on each OS. However, I didn't want to hard-code Python versions and similar into the workflow: I want cibuildwheel to take care of things like that for me.

Fortunately, GitHub Actions supports dynamically generating matrices, so I wrote a script that integrates with cibuildwheel to get the list of builds, and it then generates a matrix with one job per wheel.

* GitHub Action workflow: https://github.com/mwilliamson/jq.py/blob/5e0756dada43e11d83469d5123ca25cd1fbe397e/.github/workflows/build.yml
* Script to generate the matrix: https://github.com/mwilliamson/jq.py/blob/5e0756dada43e11d83469d5123ca25cd1fbe397e/build-wheels-matrix.py

Is this something that anyone else has done? Are there better ways of doing the same thing? Is this something that others would find  useful as an example or somesuch? Or is this just a terrible idea?

**Comment by henryiii** [comment]
🤯 I didn’t know you could do that… this would be a handy composite action! I’d like some way to do a little grouping too, I think (like by Python version), but not critical.

This seems really potentially useful. I wonder if we can simplify this a bit in a generic way? Maybe a way to format print-build-identifiers?

**Reply by henryiii** [reply]
Also seems useful for nox & tox…

**Reply by mwilliamson** [reply]
I think there a few different options for what might be useful in terms of the CLI:

* Providing a way to get all of the build identifiers at once, across platforms and architectures
* Providing a way to get all of the build identifiers according to a matrix (in the case of the jq bindings, that would be something like "linux on amd64 and aarch64, and macos on amd64")
* Formatting the build identifiers so that relevant bits of information (e.g. the architecture) can be extracted without having to interpret the identifier itself
* Adding support directly into cibuildwheel for outputting the GitHub Actions matrix

I suppose one question I have is whether importing cibuildwheel as a library (as I've done) is actually supported, or whether that's relying on internal implementation and therefore brittle? If just using the CLI would be ideal, then if JSON was outputted then something like jq (as in the actual CLI, not the bindings) could be used to turn that into a matrix that GitHub Actions understands, so you wouldn't need to have a script in a separate file. Having said that, that jq program might be a bit ugly to write, since it'd have to do things like translate from a cibuildwheel platform to a GitHub Actions OS, unless CI system-specific fields were included in the JSON output?

**Reply by henryiii** [reply]
I’ll respond in a bit, but do you have a quick text example of the output it needs to print?

**Reply by henryiii** [reply]
I think we want to avoid anything too specific to one CI service if we can - but I think we can. It might be fine to still run this per platform, since you'll need to inject a runner image anyway. Even if you make this specific to GHA, there are multiple choices for platforms (`-latest` vs. a specific version, for example).

Are you aware of this ability on any other services? I'd expect it's possible at least on Azure. I'd also still like to see a rendered example of what it's making.

**Reply by henryiii** [reply]
Here's a proof of concept:

```console
$ cibuildwheel --print-build-identifiers '{{"identifier": "{identifier}", "arch":"{arch}", "os": "ubuntu-latest"}}' --platform linux
{"identifier": "cp36-manylinux_x86_64", "arch":"x86_64", "os": "ubuntu-latest"}
{"identifier": "cp37-manylinux_x86_64", "arch":"x86_64", "os": "ubuntu-latest"}
{"identifier": "cp38-manylinux_x86_64", "arch":"x86_64", "os": "ubuntu-latest"}
{"identifier": "cp39-manylinux_x86_64", "arch":"x86_64", "os": "ubuntu-latest"}
{"identifier": "cp310-manylinux_x86_64", "arch":"x86_64", "os": "ubuntu-latest"}
{"identifier": "cp311-manylinux_x86_64", "arch":"x86_64", "os": "ubuntu-latest"}
{"identifier": "cp36-manylinux_i686", "arch":"i686", "os": "ubuntu-latest"}
{"identifier": "cp37-manylinux_i686", "arch":"i686", "os": "ubuntu-latest"}
{"identifier": "cp38-manylinux_i686", "arch":"i686", "os": "ubuntu-latest"}
{"identifier": "cp39-manylinux_i686", "arch":"i686", "os": "ubuntu-latest"}
{"identifier": "cp310-manylinux_i686", "arch":"i686", "os": "ubuntu-latest"}
{"identifier": "cp311-manylinux_i686", "arch":"i686", "os": "ubuntu-latest"}
{"identifier": "pp37-manylinux_x86_64", "arch":"x86_64", "os": "ubuntu-latest"}
{"identifier": "pp38-manylinux_x86_64", "arch":"x86_64", "os": "ubuntu-latest"}
...
```

`--print-build-identifiers` already respects `CIBW_BUILD`/`SKIP`, python version limits, etc. so that all still works.

Would this be easy to combine into the proper output, probably with `jq -s`?

**Reply by henryiii** [reply]
Such as:

```console
$ cibuildwheel --print-build-identifiers '{{"CIBW_BUILD": "{identifier}", "CIBW_ARCHS":"{arch}", "os": "ubuntu-latest"}}' --platform linux | jq -s
[
  {
    "CIBW_BUILD": "cp36-manylinux_x86_64",
    "CIBW_ARCHS": "x86_64",
    "os": "ubuntu-latest"
  },
  {
    "CIBW_BUILD": "cp37-manylinux_x86_64",
    "CIBW_ARCHS": "x86_64",
    "os": "ubuntu-latest"
  },
  ...
```

**Reply by henryiii** [reply]
Proof of concept code in https://github.com/pypa/cibuildwheel/pull/1262.

**Reply by mwilliamson** [reply]
Yup, that looks pretty good to me. So presumably to get the full list you'd need to do something like:

```
$ MATRIX=$({
    cibuildwheel --print-build-identifiers \
        '{{"CIBW_BUILD": "{identifier}", "CIBW_ARCHS":"{arch}", "os": "ubuntu-latest"}}' --platform linux && \
    cibuildwheel --print-build-identifiers \
        '{{"CIBW_BUILD": "{identifier}", "CIBW_ARCHS":"{arch}", "os": "macos-11"}}' --platform macos ;
   } | jq -s -c)
$ echo ::set-output name=matrix::"$MATRIX"
```

**Reply by mwilliamson** [reply]
> Are you aware of this ability on any other services? I'd expect it's possible at least on Azure. I'd also still like to see a rendered example of what it's making.

I'm afraid I haven't really used any of the other services in recent years. I'm not aware of this being supported on other services, but that's likely my ignorance more than anything else.

**Reply by henryiii** [reply]
After `—-only` #1098, this could be done as:

```bash
cibuildwheel --print-build-identifiers --platform linux \
  | sed 's/^.*$/{"only": "&", "os": "ubuntu-latest"}/g' \
  | jq -s
```

(combined as above, of course)

**Reply by henryiii** [reply]
```yaml
- id: set-matrix
  run: |
    MATRIX=$(
      {
        cibuildwheel --print-build-identifiers --platform linux \
         | sed 's/.*/{"only": "&", "os": "ubuntu-latest"}/' \
        && cibuildwheel --print-build-identifiers --platform macos \
         | sed 's/.*/{"only": "&", "os": "macos-latest" }/' \
        && cibuildwheel --print-build-identifiers --platform windows \
         | sed 's/.*/{"only": "&", "os": "windows-latest" }/'
      } | jq -s -c '{"include": .}'
    )
    echo ::set-output name=matrix::"$MATRIX"
```
...
```yaml
build-wheels:
  name: Build ${{ matrix.only }}
  strategy:
    matrix: ${{ fromJson(needs.build_wheels_matrix.outputs.matrix) }}
  runs-on: ${{ matrix.os }}
  steps:
      # checkout and stuff here
    - uses: pypa/cibuildwheel@eb39da0b10a9f48015e84973545691981949b13d
      with:
        only: ${{ matrix.only }}
```


Something like this? Testing this out in https://github.com/mwilliamson/jq.py/pull/76.

**Reply by mwilliamson** [reply]
I made some tweaks to your pull request, and it seems to be working. Thanks!

**Reply by henryiii** [reply]
Continuing the idea a bit, I think this is a little simpler (and avoids `sed` in favor of `jq` again):
```yaml
- id: set-matrix
  run: |
    MATRIX_INCLUDE=$(
      {
        cibuildwheel --print-build-identifiers --platform linux \
         | jq -Rc '{"only": inputs, "os": "ubuntu-latest"}'
        && cibuildwheel --print-build-identifiers --platform macos \
         | jq -Rc '{"only": inputs, "os": "macos-latest"}'
        && cibuildwheel --print-build-identifiers --platform windows \
         | jq -Rc '{"only": inputs, "os": "windows-latest"}'
      } | jq -sc
    )
    echo ::set-output name=include::"$MATRIX_INCLUDE"
```

```yaml
build-wheels:
  name: Build ${{ matrix.only }}
  strategy:
    matrix:
      include: ${{ fromJson(needs.build_wheels_matrix.outputs.include) }}
  runs-on: ${{ matrix.os }}
  steps:
      # checkout and stuff here
    - uses: pypa/cibuildwheel@eb39da0b10a9f48015e84973545691981949b13d
      with:
        only: ${{ matrix.only }}
```

Edit: using include instead of matrix to give user more options on the matrix, like only using this for part of it or only injecting emulated runs this way.

Setting the arch's is a bit tricky for Windows, since `cibuildwheel --print-build-identifiers --platform windows` doesn't print anything unless you force the arch; `auto64` isn't picked up correctly since it's resolving to the host instead of the target. Edit: fixed in #1266.

**Reply by henryiii** [reply]
Here's a blend of "grouped" inputs and generated ones for emulated archs:

```yaml
- id: set-matrix
  run: |
    MATRIX_INCLUDE=$(
      {
        cibuildwheel --print-build-identifiers --platform linux \
         | jq -Rc '{"only": inputs, "os": "ubuntu-latest"}'
      } | jq -sc
    )
    echo ::set-output name=include::"$MATRIX_INCLUDE"
  with:
    CIBW_ARCHS: aarch64
```

```yaml
build-wheels:
  name: Build ${{ matrix.os }} ${{ matrix.only }}
  strategy:
    matrix:
      os: [ubuntu-latest, macos-latest, windows-latest]
      only: [""]
      include: ${{ fromJson(needs.build_wheels_matrix.outputs.include) }}
  runs-on: ${{ matrix.os }}
  steps:
      # checkout and stuff here
    - uses: pypa/cibuildwheel@eb39da0b10a9f48015e84973545691981949b13d
      with:
        only: ${{ matrix.only }}
```
