### DISCUSSION TITLE
Shell variables not inherited by cibuildwheel action

### DISCUSSION THREAD

**Discussion by gnikit** [pypa/cibuildwheel#1439] [Q&A] [answered]
### Description

Using a custom default shell in the workflow does not seem to be inherited by the cibuildwheel action.
Find below a MWE of a workflow that requires the msys2 shell on Windows which fails when using the action but succeeds if instead one uses `pipx run cibuildwheel`

```yml
name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.sys.os }}
    runs-on: ${{ matrix.sys.os }}
    strategy:
      fail-fast: false
      matrix:
        sys:
          - { os: windows-2019, shell: "msys2 {0}" }
          - { os: ubuntu-20.04, shell: bash }
    defaults:
      run:
        shell: ${{ matrix.sys.shell }}
    steps:
      - uses: actions/checkout@v3

      - if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          path-type: inherit
          install: >-
            mingw-w64-x86_64-gcc-fortran

      - name: Build wheels
       # Using a direct call to pipx works
       # run: |
       #   pipx run cibuildwheel
        uses: pypa/cibuildwheel@v2.12.0
        env:
          CIBW_ARCHS_WINDOWS: auto64
          CIBW_ENVIRONMENT_WINDOWS: CC=gcc CXX=g++ FC=gfortran

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

```

### Build log

https://github.com/awvwgk/fpm-on-wheels/actions/runs/4473871284/jobs/7861729714
