### DISCUSSION TITLE
How come my arm64 Apple silicon wheels are not building?

### DISCUSSION THREAD

**Discussion by adam2392** [pypa/cibuildwheel#1457] [Q&A]
I'm trying to use cibuildwheel to build Apple M1 wheels for my package, but for some reason they are not working.

The PR branch I'm working off of is: https://github.com/neurodata/scikit-tree/pull/59

The associated build wheels GH actions yaml file is: https://github.com/neurodata/scikit-tree/blob/eef6c7c42636371940ac9e2a309c3038e9e422e3/.github/workflows/build_wheels.yml

I'm a bit of a novice and couldn't find necessary documentation on this in the setup docs, but maybe I looked incorrectly? Any help would be much appreciated!

**Comment by henryiii** [comment]
I don't know from that what is failing, but I see you are using Poetry - you might want to look at #1416 and related issues. Poetry doesn't really support cross compiling - you probably need to retag the wheels it produces.

**Reply by adam2392** [reply]
I actually use meson-Python. The poetry is just there but prolly will get deleted if they end up not supporting diff build backends. 

I just added the arm64 option to the matrix of OS but no arm64 Mac OS build is getting triggered. I'm not sure if there's anything special I have to do? 

Lmk if you need me to link more info. This CI build wheel tool is super slick but also new to me.

**Reply by henryiii** [reply]
I'd highly recommend using a more traditional matrix, not arrays. It would then be much clearer what you did wrong. You added an extra item to the array but you never use it.

```yaml
      matrix:
        os: # see scipy wheels.yml GH actions
          - [ubuntu-22.04, manylinux, x86_64]
          - [macos-11, macosx, x86_64, arm64]
          - [windows-2019, win, AMD64]

        python: [["cp39", "3.9"], ["cp310", "3.10"], ["cp311", "3.11.0-alpha - 3.11.0"]]
        # python[0] is used to specify the python versions made by cibuildwheel
```

But you are using `matrix.os[0]`, `matrix.os[1]`, and `matrix.os[2]`, but never `matrix.os[3]` (it normally doesn't exist!). Python is also more complex than it needs to be, and you do _not_ need to get a matching host Python for cibuildwheel to work.

Instead, I'd get rid of the arrays and try to use simple values. Then you can `include:` any extra arrangements you need.
