### DISCUSSION TITLE
3.12 not build?

### DISCUSSION THREAD

**Discussion by nschloe** [pypa/cibuildwheel#1568] [Q&A] [answered]
I just wanted to try out the new Python 3.12 support. When building from gh-actions with the config

```yaml
- name: Build wheels
  uses: pypa/cibuildwheel@v2.15.0
  env:
    CIBW_BUILD_VERBOSITY: 3
    CIBW_PROJECT_REQUIRES_PYTHON: ">=3.7, <=3.12"
    CIBW_ENVIRONMENT: >
      CFLAGS='-s'
      CXXFLAGS='-s'
    CIBW_SKIP: "pp37* pp38*"

    CIBW_ARCHS_WINDOWS: auto64
    CIBW_ARCHS_LINUX: auto64
    CIBW_ARCHS_MACOS: x86_64 arm64

    CIBW_TEST_REQUIRES: pytest
    CIBW_TEST_COMMAND: "pytest {project}/tests/"
    CIBW_TEST_SKIP: "*-macosx_arm64"
```

though, I'm only getting 3.7 to 3.11. The same is true when adding 

```yaml
    CIBW_BUILD: cp37-* cp38-* cp39-* cp310-* cp311-* cp312-*
```

Any idea why that might be? (`actions/setup-python` has `python-version` 3.11.)
