### DISCUSSION TITLE
Use Clang 16 in MacOS

### DISCUSSION THREAD

**Discussion by gurgenyegoryan** [pypa/cibuildwheel#1601] [Q&A]
Hello everyone, to build my MacOS projects I need to use GCC>=12. On x86_64 platforms, everything works, but on ARM, the build passes, but during repair_wheel, it gives an error. 
### GitHub action
```
- name: Build wheels
  run: python -m cibuildwheel
  env:
     CIBW_ENVIRONMENT_MACOS: CC=/usr/local/bin/gcc-13 CXX=/usr/local/bin/g++-13 LD_LIBRARY_PATH=/usr/local/lib
```
### Repair wheel command
```
repair-wheel-command = "delocate-wheel -w fixed_wheels --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"
```

### Error
```
delocate.delocating.DelocationError: Some missing architectures in wheel
Required arch arm64 missing from /usr/local/Cellar/gcc/13.1.0/lib/gcc/current/libstdc++.6.dylib
```

Can you help me figure out what I'm doing wrong? For an alternative, I can use Clang 16, install it with `brew install llvm`, but in this case it gives an error during the build.

### GitHub action
```
- name: Build wheels
  run: python -m cibuildwheel
  env:
      CIBW_ENVIRONMENT_MACOS: CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++ LIBRARY_PATH=/usr/local/Cellar/llvm/16.0.6/lib:$LIBRARY_PATH
```
### Error
```
/usr/local/opt/llvm/bin/clang++ -bundle -undefined dynamic_lookup -g -arch arm64 build/temp.macosx-11.0-arm64-cpython-39/python/lib.o -o build/lib.macosx-11.0-arm64-cpython-39/usearch/compiled.cpython-39-darwin.so -lomp
        ld: warning: ignoring file /usr/local/Cellar/llvm/16.0.6/lib/libomp.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
        ld: in '/usr/local/Cellar/llvm/16.0.6/lib/libunwind.dylib', building for macOS-arm64 but attempting to link with file built for macOS-x86_64
        clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
        error: command '/usr/local/opt/llvm/bin/clang++' failed with exit code 1
        [end of output]
```
