### DISCUSSION TITLE
macOS falls back to 10.9

### DISCUSSION THREAD

**Discussion by nschloe** [pypa/cibuildwheel#1636] [Q&A] [answered]
I build my wheels with

```yaml
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.1
        env:
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {project}/tests"
          CIBW_ARCHS_MACOS: x86_64 arm64
```
My `pyproject.toml` has

```toml
[tool.cibuildwheel]
build-verbosity = 1
test-requires = "pytest"
test-command = "pytest {project}/tests"

# Needed for full C++17 support
[tool.cibuildwheel.macos.environment]
MACOSX_DEPLOYMENT_TARGET = "10.14"
```

Curiously, on macOS it reports

```
[...]
Building cp38-macosx_x86_64 wheel
CPython 3.8 macOS x86_64

Installing Python cp38...
  
  + pkgutil --pkgs
  + Download https://www.python.org/ftp/python/3.8.10/python-3.8.10-macosx10.9.pkg to
[...]
```

Apparently it falls back to the ancient macOS 10.9, causing further problems down the line.

Any idea why this might be happening?

**Comment by henryiii** [comment]
CPython only ships a 10.9 binary. It works for future macOS. What problem are you having?

**Reply by nschloe** [reply]
Nanobind needs C++17, and consequently a more recent macOS version (10.14). See https://github.com/wjakob/nanobind/discussions/312.

**Reply by mayeut** [reply]
MACOSX_DEPLOYMENT_TARGET = "10.14" should be enough. 10.9 is the minimum supported by this installer, it should not prevent to build 10.14 targeted code.
Is the repo public ? If yes please do add a link.
If it's not public, can you derive a non working test case from https://github.com/pypa/cibuildwheel/blob/fff9ec32ed25a9c576750c91e06b410ed0c15db7/test/test_cpp_standards.py#L110

**Reply by nschloe** [reply]
I've contructed an MWE [here](https://github.com/nschloe/macos-test/actions/runs/6398931908). By bisecting, I've found that the `CFLAGS`
```yaml
          CIBW_ENVIRONMENT: >
            CFLAGS='-s'
            CXXFLAGS='-s'
```
seem to make a difference. When present, the cibuildwheel chooses macosx 10.9. Is this a bug?

Besides that, settings those compiler flags might not be the correct way of stripping debug symbols.

**Reply by henryiii** [reply]
Setting CIBW_ENVIRONMENT overrides `tool.cibuildwheel.*environment` values. So you are losing the value by setting it this way.

Scikit-build-core already passes `--strip` when installing, do you need to pass `-g0`?

**Reply by henryiii** [reply]
We've thought about ways to merge values, but none of them have looked all that nice. The problem is if we merged by default, there'd be no way to delete an environment variable via an override.

**Reply by Czaki** [reply]
> seem to make a difference. When present, the cibuildwheel chooses macosx 10.9. Is this a bug?

It may overwirrite `--macosx-version-min` flag that is used by part of build system to pass information about deployment target.

**Reply by henryiii** [reply, marked as answer]
No, it's supported this way, the problem is the environment is set to CFLAGS/CXXFLAGS, and the MACOSX_DEPLOYMENT_TARGET is not present, since the environment variable has overridden the toml file setting.


```yaml
CIBW_ENVIRONMENT: >
            CFLAGS='-s'
            CXXFLAGS='-s'
            MACOSX_DEPLOYMENT_TARGET='10.14'
```

Would fix it, for example.

**Reply by nschloe** [reply]
> Setting CIBW_ENVIRONMENT overrides tool.cibuildwheel.*environment values. So you are losing the value by setting it this way.

Aha! I hadn't realized that all other settings are overridden.

> Scikit-build-core already passes --strip when installing, do you need to pass -g0?

I absolutely do not want to ship debug symbols, and I'd like to have that explicit somewhere in my own code. That's why I put the flags there.

**Reply by henryiii** [reply]
It’s the default, but:

```toml
[tool.scikit-build]
install.strip = true
```

would make it explicit.
