### DISCUSSION TITLE
Using cibuildwheel on a Gitlab instance behind a corporate proxy

### DISCUSSION THREAD

**Discussion by leducvin** [pypa/cibuildwheel#1663] [Show and tell]
I am writing this to document how I could use cibuildwheel behind a corporate proxy (at least in Gitlab).

I couldn't find any information in the docs about this, nor in the Github issues or discussions.

Initially, I would get an HTTP 504 error (that was from my proxy). As I progressed with configuring this, I also got HTTP 502, and  pip errors basically saying pip couldn't find packages.

Anyway, what I found is that I need to define the proxy environment variables and make sure they are passed to the container doing the build.

In particular, `NO_PROXY` must contain `docker` for the python container to be able to reach the dind container.

Also, I needed to implement docker-specific proxy configuration in `.docker/config.json`. I used `CIBW_BEFORE_ALL` for this.

```yaml
# .gitlab-ci.yml

build-linux:
  image: python:3.8
  # make a docker daemon available for cibuildwheel to use
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
    CIBW_BEFORE_ALL: >
      mkdir -p .docker &&
      echo "{"proxies":{"default":{"httpProxy": "http://10.9.8.7:8080", "httpsProxy": "http://10.9.8.7:8080", noProxy: "localhost,127.0.0.0/8,docker"}}}" > .docker/config.json
    CIBW_ENVIRONMENT_PASS_LINUX: HTTP_PROXY HTTPS_PROXY NO_PROXY
    HTTP_PROXY: http://10.9.8.7:8080
    HTTPS_PROXY: http://10.9.8.7:8080
    NO_PROXY: localhost,127.0.0.0/8,docker
  script:
    - curl -sSL https://get.docker.com/ | sh
    - python -m pip install cibuildwheel==2.16.2
    - cibuildwheel --output-dir wheelhouse
  artifacts:
    paths:
      - wheelhouse/
```
