### DISCUSSION TITLE
MacOS arch is not set for CIBW_BEFORE_BUILD

### DISCUSSION THREAD

**Discussion by Unmoon** [pypa/cibuildwheel#1761] [Q&A]
I have a Gitlab CI pipeline like following, on an M1 runner, where I had to add `arch -x86_64` to `CIBW_BEFORE_BUILD` in order to install a package to the environment. I would expect this to not be needed.

```
  variables:
    CIBW_BUILD: "cp39*"
    CIBW_ARCHS: "x86_64"
    CIBW_BEFORE_BUILD: "arch -x86_64 ./before_build.sh"
  script:
    - softwareupdate --install-rosetta --agree-to-license
    - python3 -m pip install cibuildwheel
    - python3 -m cibuildwheel --output-dir wheelhouse
```
