### DISCUSSION TITLE
Setting up MacOS builds correctly under v2.17.0

### DISCUSSION THREAD

**Discussion by ajfriend** [pypa/cibuildwheel#1806] [Q&A]
Hi folks, thanks for all the work on this great tool!

I'm in the middle of migrating our project to the `pypa/cibuildwheel@v2.17.0` GitHub action here: https://github.com/uber/h3-py/pull/359

I've got it working, but wanted to post here to see if anyone had the time to give us a quick review that we're doing things correctly and efficiently. A few of the questions:

1. Am I splitting up the wheels across macOS 13 and 14 correctly with:

```yaml
strategy:
  matrix:
    include:
      - os: macos-13
        build: 'cp*-macosx_x86_64'
        name: macOS13
      - os: macos-14
        build: 'cp*-macosx_arm64'
        name: macOS14
```

2. And am I correct in thinking that I no longer need `CIBW_ARCHS_MACOS: x86_64 arm64` when doing it this way?

3. We still break up the longer builds as introduced with https://github.com/uber/h3-py/pull/189. Is that still the best way to do things? Is there any way to make that less verbose, or new tricks to speed up the slower builds?
