### DISCUSSION TITLE
Building for `windows-arm64` with `setuptools-rust` on github actions

### DISCUSSION THREAD

**Discussion by MusicalNinjaDad** [pypa/cibuildwheel#1814] [Q&A]
Hi,
cibuildwheel is amazing and really makes life easy. Thanks!

I'm trying to take advantage of the experimental arm64 support for windows and the build is failing with the error:

```text
libpyo3_ffi-237e52e263bcae53.rlib(pyo3_ffi-237e52e263bcae53.pyo3_ffi.446da754e7879e6-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol PyCapsule_Import referenced in function _ZN8pyo3_ffi8datetime17PyDateTime_IMPORT17he75050a916d9c6d9E
C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\python.3.9.10\tools\libs\python39.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'ARM64'
D:\a\FizzBuzz\FizzBuzz\target\aarch64-pc-windows-msvc\release\deps\fizzbuzzo3.dll : fatal error LNK1120: 201 unresolved external
```

Here's the exctract from `pyproject.toml`

```toml
[[tool.setuptools-rust.ext-modules]]
# Private Rust extension module to be nested into the Python package
target = "fizzbuzzo3"  # The last part of the name (e.g. "_lib") has to match lib.name in Cargo.toml,
                             # but you can add a prefix to nest it inside of a Python package.
path = "fizzbuzzo3/Cargo.toml"      # Default value, can be omitted
binding = "PyO3"         # Default value, can be omitted
features = ["pyo3/extension-module"]

[tool.cibuildwheel]
skip = "*-musllinux_i686" # No musllinux-i686 rust compiler available.
linux.before-all = "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal"
linux.environment = { PATH="$HOME/.cargo/bin:$PATH" }
macos.before-all = "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal"
windows.before-all = "rustup target add aarch64-pc-windows-msvc i586-pc-windows-msvc i686-pc-windows-msvc x86_64-pc-windows-msvc"
windows.archs = "all"
# test-skip = "*-win_arm64" # commented out to check that expected warning occurs
```

and the job from the github workflow:

```yaml
  wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
```

Has anyone had success building for windows-arm64? I'm using `features = ["pyo3/extension-module"]` which should stop linking to the python libraries (and this worked to resolve earlier errors on manylinux builds which were caused by incorrectly trying to link to python)

Thanks!
