### DISCUSSION TITLE
Build Python C extension under windows

### DISCUSSION THREAD

**Discussion by emcek** [pypa/cibuildwheel#2039] [Q&A] [answered]
I try build/compile wheels for `lupa` under windows. I got one working job in [github-action](https://github.com/emcek/pyi/actions/runs/11264308367) `manual` for Python 3.6.

I needed replace original `setup.py` to be able build `luajit` wheel for windows, line 370 is different:
```diff
-or (platform.startswith('win') and 'luajit' in os.path.basename(lua_bundle_path.rstrip(os.sep)))
+or (get_machine() != "AMD64" and  get_machine() != "x86_64" and 'luajit' in os.path.basename(lua_bundle_path.rstrip(os.sep)))
```

So, I try use `cibuildwheel` to build for all Pythons 3.6-3.12 but it failed with:
```console
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120
```

See loggs in CI jobs.

I guess key command from manual step is:
```console
python setup.py build_ext -i bdist_wheel --use-bundle --with-cython
```

Anybody have any idea why it failed, looks like misconfiguration???

**Note:** It is important (for me) to build `luajit21` module (since it the fastest). In manual step I was able to successfully build all modules: `luajit21`, `luajit20`, `lua54`-`lua51`
When I install `lupa-2.2-cp36-cp36m-win_amd64.whl` from manual job, all imports are working:
```python
import lupa.luajit21
import lupa.luajit20
import lupa.lua54
import lupa.lua53
import lupa.lua52
import lupa.lua51
```

**Comment by emcek** [comment, marked as answer]
The trick is add before `cibuildwheel` job:
```yaml
- name: "VS setup env"
  uses: TheMrMilchmann/setup-msvc-dev@v3
  with:
    arch: x64
```
It just run `vcvars64.bat` and does nothing on Linux/Mac.

For the record none of is working:
```yaml
env:
  CIBW_BEFORE_BUILD_WINDOWS: call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
  CIBW_BEFORE_ALL_WINDOWS: call C:\"Program Files"\"Microsoft Visual Studio"\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat
```
