### DISCUSSION TITLE
How to use `manylinux_2_34`?

### DISCUSSION THREAD

**Discussion by agarny** [pypa/cibuildwheel#2129] [Q&A] [answered]
Hi,

I have a C++-based project that relies on various third-party libraries. On Linux, everything is built on Ubuntu 22.04. When it comes to Python bindings, I use `nanobind` and it's all working fine.

However, now, I want to use `cibuildwheel` to get Python weels for my project and this is where I am having problems. I am getting undefined references for both `__libc_single_threaded` and `mallinfo2`.

It all used to be fine when I was building things on Ubuntu 20.04, but that version of Ubuntu is now a bit old and I would like to support Ubuntu 22.04 and later.

I am using `cibuildwheel` 2.22.0 with `manylinux_2_28`, but I understand that this version of manylinux is not recent enough for my needs? It looks like I need at least `manylinux_2_34` (see [here](https://github.com/pypa/manylinux/issues/1585)), but again it looks like `manylinux_2_34` didn't make it in time for `cibuildwheel` 2.22.0 (see [here](https://github.com/pypa/cibuildwheel/pull/2098)).

So, assuming I have got things right (?), what are my options?

Cheers, Alan.

**Comment by agarny** [comment, marked as answer]
Ok, I hadn't thought of it, but I was using the following in my GitHub workflow:
```yaml
- name: Build Python wheels
  uses: pypa/cibuildwheel@v2.22.0
  env:
    CIBW_ARCHS: auto64
    CIBW_BUILD: 'cp*'
    CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=13.0
    CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_34
    CIBW_SKIP: 'cp36* cp37* cp38* *musllinux*'
```
and then wondered whether I could use the commit version that adds support for `manyline_2_34`, i.e.
```yaml
- name: Build Python wheels
  uses: pypa/cibuildwheel@9c75ea15c2f31a77e6043b80b1b7081372319d85
  env:
    CIBW_ARCHS: auto64
    CIBW_BUILD: 'cp*'
    CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=13.0
    CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_34
    CIBW_SKIP: 'cp36* cp37* cp38* *musllinux*'
```
and... sure enough, it's all working fine for me now. 🥳
