### DISCUSSION TITLE
Github suddenly got segfaulty?

### DISCUSSION THREAD

**Discussion by dvarrazzo** [pypa/cibuildwheel#2256] [Q&A] [answered]
Hello,

Psycopg 3 is configured to build binary packages weekly, and [the last job](https://github.com/psycopg/psycopg/actions/runs/12972574287) is showing segfaults in manylinux builds for ppc64le and aarch64 platforms. [The same job](https://github.com/psycopg/psycopg/actions/runs/12851489204) last week didn't show any failure and there was no change in the code between the two.

I have attached the logs of the **ppc64le, cp39, manylinux** run. These logs have timestamps stripped and few other irrelevant differences removed (such as the order of the docker layers pulled) for ease of comparison: 

- [job-logs-good.txt](https://github.com/user-attachments/files/18573399/job-logs-good.txt) is [the successful job](https://github.com/psycopg/psycopg/actions/runs/12851489204/job/35836891461);
- [job-logs-bad.txt](https://github.com/user-attachments/files/18573398/job-logs-bad.txt) is [attempt 3 of the failed job](https://github.com/psycopg/psycopg/actions/runs/12972574287/attempts/3), which had some libraries cached;
- [job-logs-bad-2.txt](https://github.com/user-attachments/files/18573396/job-logs-bad-2.txt) is [attempt 4 of the failed job](https://github.com/psycopg/psycopg/actions/runs/12972574287/attempts/4), run after cleaning the cache, with all depending libraries built from sources.

Does anyone see anything obvious about the segfaults?

Thank you very much!

**Comment by joerick** [comment, marked as answer]
I believe you're hitting a bug around setup-qemu-action. I didn't see it myself but @mayeut just pushed this fix to our repo-

https://github.com/pypa/cibuildwheel/pull/2253/commits/4538497e648c6856ad8ae129e7871c6bace7ce07

The referenced issues are https://github.com/docker/setup-qemu-action/issues/188 and https://github.com/tonistiigi/binfmt/issues/215. @mayeut's workaround is the following in a github workflow-

```yaml
    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v3
      with:
        # This should be temporary
        # xref https://github.com/docker/setup-qemu-action/issues/188
        # xref https://github.com/tonistiigi/binfmt/issues/215
        image: tonistiigi/binfmt:qemu-v8.1.5
```
