### DISCUSSION TITLE
cibuildwheel thinks I am building pure Python wheels even with the inclusion of shared library files

### DISCUSSION THREAD

**Discussion by guoalex1** [pypa/cibuildwheel#2354] [General]
This may be an issue with Hatch (my [post](https://github.com/pypa/hatch/issues/1955) there explaining my situation is copied below)

> I am building a simple C extension module that dynamically loads shared libraries via a ctypes wrapper. I am following the tutorial [here](https://packaging.python.org/en/latest/tutorials/packaging-projects/#choosing-build-backend) to publish onto TestPyPi, which recommends building with hatch.
> 
> The relevant parts of my pyproject.toml are here:
> 
> ```
> [build-system]
> requires = ["hatchling >= 1.26"]
> build-backend = "hatchling.build"
> 
> [tool.hatch.build.targets.wheel]
> artifacts = [
>   "package/*.so",
>   "package/*.dll",
>   "package/*.dylib"
> ]
> ```
> 
> and my package directory includes my wrapper, an **init**.py file, and the appropriate shared library.
> 
> When I run `python3 -m build`, it generates a .whl file with a none-any tag, even though (I have checked) the .so/.dll file is included in the generated tar.gz file. It is also in the wheel as after I upload to TestPyPi and install it, the shared library file is included with the package and it runs fine.
> 
> As I understand, the inclusion of a non-Python file should make Hatch recognize it as not a pure build since my shared library obviously cannot be run on any OS. Eventually this process will be automated with GitHub Actions and cibuildwheel, but I'd like to understand how I can build a platform specific wheel with Hatch.
> 
> (I am aware of the method of using a dummy C file or just renaming the file, but I am looking for a more natural way to do this)

My strategy is below (a modified version of [this example](https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml)):

```
jobs:
  build:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        os: [linux-intel, windows]
        include:
          - archs: auto
            platform: auto
          - os: linux-intel
            runs-on: ubuntu-latest
          - os: windows
            runs-on: windows-latest
```

The code below is the relevant part that calls cibuildwheel after everything in the package directory is setup:

```
- name: Build wheels
  uses: pypa/cibuildwheel@v2.23.2
  env:
    CIBW_PLATFORM: ${{ matrix.platform }}
    CIBW_ARCHS: ${{ matrix.archs }}
    CIBW_BUILD_VERBOSITY: 1
```

The action always fails immediately due to this message:

Build failed because a pure Python wheel was generated.

If you intend to build a pure-Python wheel, you don't need
cibuildwheel - use `pip wheel .`, `pipx run build --wheel`, `uv
build --wheel`, etc. instead. You only need cibuildwheel if you
have compiled (not Python) code in your wheels making them depend
on the platform.

As mentioned in my other post, this may be an issue with Hatch, but given that I can verify that it is able to include the shared library in the package, I am hoping someone can point me in the right direction on how to produce a platform specific wheel.
