### DISCUSSION TITLE
How to set the DYLD_LIBRARY_PATH automatically?

### DISCUSSION THREAD

**Discussion by npfp** [pypa/cibuildwheel#2445] [Q&A]
Hello,

I'm using `cibuildwheel` to build and repair a wheel that is built using `cmake`, `pybind11`, `scikit-build-core` and `uv`.

The C++ code depends on some external libraries that are fetched and built as part of the compilation of the project. The shared libraries generated are stored in the `uv-build` folder (see the `[tool.scikit-build]` entry).

```
[tool.scikit-build]
sdist.cmake = true
wheel.expand-macos-universal-tags = true
minimum-version = "build-system.requires"
wheel.packages = ["my_package"]
build-dir = "uv-build"
cmake.build-type = "Release"
```

Locally (on Mac), I had to set manually `DYLD_LIBRARY_PATH` to `***/uv-build/lib` so the manual execution of `delocate` could fix the wheel. (I can't test `cibuildwheel` locally because I had to revert delocate to the previous version because of this bug: https://github.com/matthew-brett/delocate/issues/247)

My question is: how to do the same in the CI (linux and Mac)?

I tried something like:

```
[tool.cibuildwheel.linux]
repair-wheel-command = "DYLD_LIBRARY_PATH=$REPAIR_LIBRARY_PATH auditwheel repair -w {dest_dir} {wheel}"

[tool.cibuildwheel.macos]
repair-wheel-command = "DYLD_LIBRARY_PATH=$REPAIR_LIBRARY_PATH delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"
```
where
```
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_MANYLINUX_I686_IMAGE: manylinux_2_28
          REPAIR_LIBRARY_PATH: /project/cpp/uv-build/lib #${{ github.workspace }}/cpp/uv-build/lib
```
but with no luck. 

I'm sure I'm missing something obvious so any clue would be much appreciated!
