### DISCUSSION TITLE
Automatic updating ideas

### DISCUSSION THREAD

**Discussion by henryiii** [pypa/cibuildwheel#492] [Ideas]
I'd like to propose we add a Javascript action file for cibuildwheel. It would look like this:

```yaml
- uses: joerick/cibuildwheel@v1.7.1
  with:
    args: .
```

Maybe we could come up with some useful features here (at at least it does combine the download and run step), but there's one _very_ useful feature this alone gives us - dependabot support! You can setup GitHub's dependabot to update your actions files once a day, a week, or a month, and it makes a PR whenever actions update. See https://github.com/scikit-hep/boost-histogram/pull/466.

It does support Python as well, but I don't know a way to get it to look into an action file for `pip install cibuildwheel==X` and update X.

I've seen a lot of old pinned versions of cibuildwheel around when looking at projects, this would give a way for them to opt in to automatic updates in a controlled (PR) fashion.

Thoughts? Any reason this might not work?

**Comment by YannickJadoul** [comment]
I think it would be a nice feature, yes! Even if it would just nicely integrate into GHA, then (even though `pip install` and `cibuildwheel` is reasonably compact as well). Any idea how much code/maintenance this would be?

Also, does it need to be a JS action; it can't just be a ["composite run steps action"](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-composite-run-steps-action)? (I'm guessing the dependabot won't work then? But no experience, so just checking to be explicit, here.)

> Maybe we could come up with some useful features here 

Adding options, instead of stuffing them into environment variables, maybe?

```yaml
- uses: joerick/cibuildwheel@v1.7.1
  with:
    args: .
    options:
      CIBW_SKIP: cp27-*
      # Etc
```

Not sure if that now makes it so much cleaner than just an extra step to set the environment variables, though...

**Reply by henryiii** [reply]
I think that's a new action type, it used to be Docker and JS. But I don't think you'd have access to the version info, so it would have to be burned in. But that might not be bad?

**Reply by YannickJadoul** [reply]
Hmmm, I don't know. I was mainly hoping there'd be a way to avoid JS ;-)

**Reply by henryiii** [reply]
I feel like the version number is in a lot of locations already (don't see bump2version config anywhere, so maybe it's grepped every time?), so adding it in one more place wouldn't likely be bad, and this would then be _very_ simple.

**Reply by YannickJadoul** [reply]
It's actually always been @joerick doing this, so I'm not sure.

Ah, no, it's here, apparently: https://github.com/joerick/cibuildwheel/blob/master/bin/bump_version.py

**Reply by henryiii** [reply]
Oh, wow, okay. It could be added there, then.

**Reply by joerick** [reply]
Of the options presented here, I like the GHA custom action the best. Previously, we've looked at Azure Pipelines template configs, which looked really simple for the simple case, but if you needed to customise something that wasn't supported by the template you were back to square one.

As an action in GHA, I like that it can be composed into an existing workflow alongside other steps, so users can do things like 'run my tests, if they pass, invoke cibuildwheel'. And, the expression syntax could be used to fill in cibuildwheel's options from a user-specified matrix. Cool.

I'm not too worried about it being in JS myself (I do a lot of it in the day-job). I can set up a Typescript project like [this one](https://github.com/joerick/pr-labels-action), which contributors might find a little more ergonomic (?) than plain old JS.

One question - would a Github action incorporate the `runs-on:` matrix, or would that config still be external? i.e. would minimal config look like

```yaml
jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: joerick/cibuildwheel@v1.7.1
      with:
        args: .
```

or

```yaml
jobs:
  build-wheels:
    name: Build wheels
    steps:
    - uses: joerick/cibuildwheel@v1.7.1
      with:
        args: .
```

I actually think I prefer the ~latter~ former, as it's more extensible to custom workflows.

**Reply by henryiii** [reply]
I'm not sure you can incorporate the matrix, and I wouldn't do that. One of Travis's downfalls is that it was highly specific to specific cases, like Python or C++ package, and was much harder to customize to a real-world situation. Some configs today with cibuildwheel run one job per Python version, etc.; those would be hard to adapt if there are a long list of special arguments.

In fact, I think you have to be explicit about passing in external config options (and you should be, there shouldn't be "magic" named matrix options in GitHub Actions!).

 I would make the minimal config this:

```yaml
jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: joerick/cibuildwheel@v1.7.1
   - uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*
```

Actually, setup-python is optional on the GitHub runners - the default Python on runners is fine. Only needed for completeness on arbitrary runners or if someone wanted to run inside a docker container (which actions can do!).  And as long as we support the latest version or two of Python, no need to specify a python version number, really. Also setting a Python version really confuses new users who think it has something to do with the wheels produced.

Here's a rough draft of the action in composite-actions:

```yaml
name: 'cibuildwheel'
description: 'Runs cibuildwheel on the current runner'
inputs:
  package-dir:
    description: 'Input directory, defaults to "."'
    required: false
    default: '.'
  output-dir:
    description: 'Folder to place the outputs in, defaults to "wheelhouse"'
    required: false
    default: 'wheelhouse'

runs:
  using: "composite"
  steps: 
    - run: pip install cibuildwheel==1.7.1
      shell: bash
    - run: python -m cibuildwheel ${{ inputs.package-dir }} --output_dir ${{ inputs.output-dir }}
      shell: bash
```

**Reply by henryiii** [reply]
I would not want the action to become too smart - it's not supposed to make cibuildwheel GitHub action specific, it's just a minor convenience for the most popular platform, and (to me, most important) a way to get dependabot to help with updates on it!

**Reply by henryiii** [reply]
I am also assuming you have an "env" slot on actions that sets the env inside the action, as that would also be important here.

If you'd like, I could try out this action as a local action in one of my repositories and see how well it works? It would already bundle the cibuildhwheel version into one place - I've just noticed that even though I sort-of keep up the wheel version, the one in my PR tests is not updated past 1.5 :facepalm:.

**Reply by joerick** [reply]
Arg, I  misspoke!, yes I agree with you, we wouldn't want the action to be too smart. Keep the matrix external.

The composite run-steps looks good! I wonder if we can get away without doing the JS after all?

Just one thought on the action, could we do `pip install ${{ github.action_path }}` instead of `pip install cibuildwheel==version`? Then we don't need runner to go to PyPI to get the cibuildwheel source code. Might be a bit faster and would mean we don't have to write the version number in the action yaml.

**Reply by henryiii** [reply]
Composite steps can't run other actions, just `run:` steps, so I've dropped the upload artifact step. That's really for the best, anyway - actions should be composable, not all-in-one. If someone doesn't want to upload, they shouldn't have to turn it off via a special syntax, I think.

The downside is that you'd have to install from source which is slower than installing from a wheel. You don't get the pre-bytecode compiling either, but for a one-run action - that's not likely a difference, really. But on the upside, you could even force a specific commit hash, I think. Pretty sure I'm in favor of that.

**Reply by joerick** [reply]
> But on the upside, you could even force a specific commit hash

It think `${{ github.action_path }}` expands to a filesystem path to this action's code, so the version is already specified in the `uses:` option - that version tag specifies which commit to get the action code from.

**Reply by henryiii** [reply]
The run is happening here: https://github.com/scikit-hep/boost-histogram/pull/488 - So far, looks good! Nesting output is working. Passing in the env is working. I'd say that's a win!

**Reply by henryiii** [reply]
Yes, it should get all the code (I think), so I think `${{ github.action_path }}` would work. I meant you could do `uses: joerick/cibuildwheel@<hash>`, which otherwise would not have worked to get a specific commit.

**Reply by henryiii** [reply]
And it's working, PR here: https://github.com/joerick/cibuildwheel/pull/494

**Reply by YannickJadoul** [reply]
Wow. I'm very impressed by speed at which you managed this, @henryiii! :-D

**Comment by Czaki** [comment]
Maybe also provide Azure Pipelines Template https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops

Github actions still do not provide an option for restart a single job (for example after network faliture)

**Reply by henryiii** [reply]
I proposed a couple of other ideas below for how to update in general, either in addition to or in replacement of the original idea.

**Comment by henryiii** [comment]
Idea 2: we could add a pre-commit action instead. This would look like:

```yaml
repos:
- repo: https://github.com/joerick/cibuildwheel
  rev: v1.7.1
  hooks:
  - id: cibuildwheel
    files: .github/workflows/myaction.yml
```
The action would search and replace for `cibuildwheel\w*==\w*\d\.\d.\d` with the current version. Then you would update with `pre-commit autoupdate` and rerun, or you'd use pre-commit.ci to automatically make update PRs (I think it's every Sunday?).

A little more "hacky", but would work with all CIs, and we could have reasonable defaults for the files so that most common CI files would be picked up.
