### DISCUSSION TITLE
Overrides in TOML

### DISCUSSION THREAD

**Discussion by henryiii** [pypa/cibuildwheel#799] [Ideas]
I've really been enjoying [the design of MyPy's 0.9xx TOML](http://mypy-lang.blogspot.com/2021/06/mypy-0900-released.html) interface. I think the same idea could be applied to cibuildwheel, possibly. Here's my idea of what it would look like:

```toml
[tool.cibuildwheel]
# Normal options, etc.
manylinux-x86_64-image = "manylinux2010"

[[tool.cibuildwheel.overrides]]
select = "cp36-*"
manylinux-x86_64-image = "manylinux1"

[[tool.cibuildwheel.overrides]]
select = "cp310-*"
manylinux-x86_64-image = "manylinux2014"
```

Each `overrides` item overrides the matching `build` selected by the expression (analogous to `tool.mypy.overrides` and `module`). `build` could be called something else to differentiate it, or or could be `build` for similarity. Overrides are applied to every build selector they match sequentially.

This would be really useful in reducing one of the two remaining reasons to use environment variables, and would simply both CI and local builds. The fact that CPython 3.10 _can't_ build with manylinux1 makes this especially useful now (and, really, there's little point in building manylinux1 CPython 3.9 wheels either, even NumPy bumped those up to manylinux2010).

The other remaining reason for environment variables is to build two different wheels from a single identifier (like manylinux1 and manylinux2010), which this would not solve. I think this is special enough that it does not need to be addressed here.

**Comment by joerick** [comment]
I really like this idea! I had a similar idea in https://github.com/pypa/cibuildwheel/discussions/516#discussioncomment-263108, but it didn't go anywhere because it involved a total overhaul of how the options were parsed. This would fit really neatly inside the existing options structure.

A couple points on the above snippet-

  - Should we use `select`/`override` rather than `build` to say what the override refers to? Otherwise it might get confusing with the existing `build` option...
  - Should we allow `build`/`skip` in an override? My gut says that it could get messy, but something like this _could_ be useful?

    ```toml
    [[tool.cibuildwheel.overrides]]
    select = "cp36-*"
    skip = "*aarch64"
    ```

    ... I think that this shouldn't be allowed, this is better handled by `skip = "cp36-*aarch64".

The other interesting thing to talk about is implementation, because we'd have to delay evaluation of the build options until each build. That's probably fine, but presents an interesting challenge when we print the options at the start of a cibuildwheel session! Maybe there's something we can do like-

```text
Build options:
  platform: 'linux'
  architectures: {<Architecture.x86_64: 'x86_64'>, <Architecture.i686: 'i686'>}
  before_all:
    *: 'yum install libz-devel'
    cp36-*: 'yum install libz-devel && yum install sqlite'
  before_build: 'scripts/prepare'
```

**Comment by henryiii** [comment]
Actually, NumPy has bumped 3.10 up to manylinux2014, making this even nicer to have. The default manylinux 2010 build is not able to download NumPy wheels on Python 3.10.

**Reply by henryiii** [reply]
Also #627 would really benefit from this. I'll try to work on it on the same timescale as that (which looks like it will be really soon, so early next week).

**Reply by mayeut** [reply]
I'm going to experiment the musllinux build on cmake. This discussion came to mind immediately because I think (not done the work yet), it would be easier with this.

**Comment by henryiii** [comment]
A few thoughts as I've been working on the implementation. First, `before_all` and `*-image` are possibly the most important things to be able to override, and they happen to be special. Overriding the image needs to cause more image launches; you'll need to do one per every unique image name (as is done now, but currently it does not depend on the config). `before-all` applies per image, so setting a different before-all on a single should either be an error or should also cause more image launches. I think, at least for now, simply verifying it does not vary *per-image* is fine, and throwing an error if it does.

So this is valid:

```toml
[tool.cibuildwheel]
before-all = "yum install somelib"

[[tool.cibuildwheel.overrides]]
select = "cp310-*"
manylinux-x86_64-image = "manylinux_2_24"
before-all = "apt-get install somelib"
```

and this is an error:

```toml
[tool.cibuildwheel]
before-all = "yum install somelib"

[[tool.cibuildwheel.overrides]]
select = "cp310-*"
before-all = "apt-get install somelib"
```

We could expand this later if needed to add new docker launches if before-all changes (but this already is also how Windows and macOS would behave - there are no containers there, so they support only one before-all).

**Reply by joerick** [reply]
Ah, yes, I hadn't foreseen this complication. Good point. Just so I'm sure I understand the examples above, are you saying that it will be valid to change the image for a specific Python version? Quite a big refactor! I'm guessing you have a use-case in mind for this?

**Reply by henryiii** [reply]
Yes, the one listed above. NumPy is only shipping manylinux 2014 wheels only for Python 3.10 (since all versions of Pip that support Python 3.10 understand manylinux2014, it's a sensible thing to do), so most (all?) data-science packages will likely want to do manylinux2010 for Python 3.6-3.9, and manylinux2014 for 3.10+. Or manylinux1 for 3.6-3.8, manylinux2010 for 3.9, and manylinux2014 for 3.10+. Even without requiring NumPy for either build or test, this is still a good idea - there's little point in releasing manylinux2010 wheels for Python 3.10, unless you really do need CentOS 6 compatible wheels. On Python 3.10....

If we can't trigger splitting based on this right away, we can also make it an error for now - but I think it will be pretty easy to split by image. Let's see.

**Comment by JesseFarebro** [comment]
Is environment variable parsing supported using the TOML overrides? There's something weird going on when I try to export a host variable, e.g.,

```toml
[[tool.cibuildwheel.overrides]]
select = "*-manylinux_x86_64"

  [tool.cibuildwheel.overrides.environment]
    MY_VAR = "$MY_VAR"
```
But it doesn't seem to be exported properly.

Also, has it ever been discussed how to have a method to extend the set of environment variables? I wish the environment variables were a list of tables so I could easily append environment variables. With the current API I have copies of five or six environment variables for each override.

**Reply by henryiii** [reply]
That should be a TOML error (as in, someone needs to throw an error). Overrides is an array. You have to use the nested syntax.

```toml
[[tool.cibuildwheel.overrides]]
select = "*-manylinux_x86_64"
environment = { MY_VAR = "$MY_VAR" }
```

Due to (arbitrary) TOML restrictions, you cannot place a new line or an ending comma here. You can use a string if you prefer.

**Reply by henryiii** [reply]
The problem with extending an environment is that there's no way to undo it￼. You could set a variable to empty string, but you can't remove a variable. That said, I think I would be OK with extending rather than replacing by default, but you would lose the ability to do that. It should even be backward-compatible unless you were relying on a variable not being set.￼￼￼￼

**Reply by JesseFarebro** [reply]
If you put this into a TOML parser, e.g., [http://toml-online-parser.ovonick.com](http://toml-online-parser.ovonick.com)
```toml
[[tool.cibuildwheel.overrides]]
select = "*-manylinux_x86_64"

  [tool.cibuildwheel.overrides.environment]
    MY_VAR = "$MY_VAR"

[[tool.cibuildwheel.overrides]]
select = "*-macos_x86_64"

  [tool.cibuildwheel.overrides.environment]
    MY_VAR_2 = "$MY_VAR"
```
it gets parsed the same as what you suggest. It does look unusual, I just wanted a way to have environment variables over multiple lines. Inline tables can't be written over multiple lines. If we did have the notion of extending the environment I could just specify the environment table and override a single environment variable per override selection. Right now I'm stuck copying this to all my overrides.

RE: extending environment. In a lot of cases setting the env variable to an empty string would be sufficient, shell scripts at least usually use `test -n`. Another option might be to have a special key like "+environment" or something which would override the environment completely and not inherit anything.
