### DISCUSSION TITLE
PyPI: generated wheel has unsupported platform tag?

### DISCUSSION THREAD

**Discussion by biojppm** [pypa/cibuildwheel#842] [Q&A] [answered]
First, thanks for the project; it is really helpful.

In the github CI for [my project](https://github.com/biojppm/rapidyaml), I am generating the wheels using cibuildwheel:
```yaml

  python_wheels:
    name: python/${{matrix.config.pythonv}}/${{matrix.config.osname}}/${{matrix.config.arch}}
    runs-on: ${{matrix.config.os}}
    env: {DEV: OFF,
          BT: Release,
          OS: "${{matrix.config.os}}",
          PYTHONV: "${{matrix.config.pythonv}}",
          API: ON,
          CMAKE_FLAGS: "-DRYML_DEV=OFF -DRYML_BUILD_API=ON -DRYML_API_TESTS=OFF -DRYML_API_BENCHMARKS=OFF",
          CIBW_BUILD: "cp${{matrix.config.cibw_pyv}}*-${{matrix.config.cibw_platform}}",
          CIBW_ARCHS: "${{matrix.config.cibw_arch}}"}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {pythonv: 3.9 , cibw_pyv: 39 , cibw_arch: x86_64, osname: linux, cibw_platform: manylinux_x86_64, os: ubuntu-20.04}
          - {pythonv: 3.9 , cibw_pyv: 39 , cibw_arch: i686  , osname: linux, cibw_platform: manylinux_i686  , os: ubuntu-20.04}
          - {pythonv: 3.9 , cibw_pyv: 39 , cibw_arch: AMD64 , osname: win  , cibw_platform: win_amd64       , os: windows-2019, cxx: vs2019}
          - {pythonv: 3.8 , cibw_pyv: 38 , cibw_arch: x86_64, osname: linux, cibw_platform: manylinux_x86_64, os: ubuntu-20.04}
          - {pythonv: 3.8 , cibw_pyv: 38 , cibw_arch: i686  , osname: linux, cibw_platform: manylinux_i686  , os: ubuntu-20.04}
          - {pythonv: 3.8 , cibw_pyv: 38 , cibw_arch: AMD64 , osname: win  , cibw_platform: win_amd64       , os: windows-2019, cxx: vs2019}
          - {pythonv: 3.7 , cibw_pyv: 37 , cibw_arch: x86_64, osname: linux, cibw_platform: manylinux_x86_64, os: ubuntu-20.04}
          - {pythonv: 3.7 , cibw_pyv: 37 , cibw_arch: i686  , osname: linux, cibw_platform: manylinux_i686  , os: ubuntu-20.04}
          - {pythonv: 3.7 , cibw_pyv: 37 , cibw_arch: AMD64 , osname: win  , cibw_platform: win_amd64       , os: windows-2019, cxx: vs2019}
    steps:
      # use fetch-depth to ensure all tags are fetched
      - {name: checkout, uses: actions/checkout@v2, with: {submodules: recursive, fetch-depth: 0}}
      - name: install python ${{matrix.config.pythonv}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.config.pythonv}}
      - name: install requirements
        run: |
          echo "expecting python ${{matrix.config.pythonv}}..."
          python --version
          pip install -v -r requirements.txt
      - name: create wheel
        uses: joerick/cibuildwheel@v2.1.1
      # change rapidyaml-* to rapidyaml-python-*
      - name: normalize wheel file name
        id: rename
        run: |
          find . -name "*.whl"
          ln -fs ./wheelhouse ./dist
          ls dist/*.whl
          whl=`ls -1 dist/*.whl`
          [ ! -f $whl ] && exit 1
          whlr=`echo $whl | sed 's:rapidyaml-:rapidyaml-python-:'`
          mv -fv $whl $whlr
      - name: Save artifacts for publishing to PyPI
        uses: actions/upload-artifact@v1
        with: {name: dist, path: dist}
  release:
    runs-on: ubuntu-latest
    needs:
      - src
      - cpp
      - python_src
      - python_wheels
    steps:
      - name: Gather artifacts - ./assets
        uses: actions/download-artifact@v2
        with: {name: assets, path: assets}
      - name: Gather artifacts - ./dist
        uses: actions/download-artifact@v2
        with: {name: dist, path: dist}
      - name: Verify existing artifacts
        run: |
          ls -lFhp assets/
          ls -lFhp dist/
      #
      # PyPI
      - name: Publish python packages to test PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{secrets.PYPI_TOKEN_TEST}}
          repository_url: https://test.pypi.org/legacy/
          verbose: true
      - name: Publish python packages to production PyPI
        if: contains(github.ref, 'tags/v')
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{secrets.PYPI_TOKEN}}
          verbose: true
```
 I get [the following error](https://github.com/biojppm/rapidyaml/runs/3681530201?check_suite_focus=true) while trying to upload to (test) PyPI:
```console
Run pypa/gh-action-pypi-publish@v1.4.2
  with:
    user: __token__
    password: ***
    repository_url: https://test.pypi.org/legacy/
    verbose: true
    packages_dir: dist
    verify_metadata: true
    skip_existing: false
  env:
    PROJ_PKG_NAME: rapidyaml-
    PROJ_PFX_TARGET: ryml-
    PROJ_PFX_CMAKE: RYML_
    CMAKE_FLAGS: -DRYML_TEST_SUITE=OFF
    NUM_JOBS_BUILD: 
/usr/bin/docker run --name e1cc514862fc04eb3d48d2b0f615296d8828dd_ab20c0 --label e1cc51 --workdir /github/workspace --rm -e PROJ_PKG_NAME -e PROJ_PFX_TARGET -e PROJ_PFX_CMAKE -e CMAKE_FLAGS -e NUM_JOBS_BUILD -e INPUT_USER -e INPUT_PASSWORD -e INPUT_REPOSITORY_URL -e INPUT_VERBOSE -e INPUT_PACKAGES_DIR -e INPUT_VERIFY_METADATA -e INPUT_SKIP_EXISTING -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/rapidyaml/rapidyaml":"/github/workspace" e1cc51:4862fc04eb3d48d2b0f615296d8828dd  "__token__" "***" "https://test.pypi.org/legacy/" "dist" "true" "false" "true"
Checking dist/rapidyaml-python-0.2.0.post111-cp37-cp37m-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl: PASSED
Checking dist/rapidyaml-python-0.2.0.post111-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl: PASSED
Checking dist/rapidyaml-python-0.2.0.post111-cp37-cp37m-win_amd64.whl: PASSED
Checking dist/rapidyaml-python-0.2.0.post111-cp38-cp38-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl: PASSED
Checking dist/rapidyaml-python-0.2.0.post111-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl: PASSED
Checking dist/rapidyaml-python-0.2.0.post111-cp38-cp38-win_amd64.whl: PASSED
Checking dist/rapidyaml-python-0.2.0.post111-cp39-cp39-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl: PASSED
Checking dist/rapidyaml-python-0.2.0.post111-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl: PASSED
Checking dist/rapidyaml-python-0.2.0.post111-cp39-cp39-win_amd64.whl: PASSED
Checking dist/rapidyaml-python-0.2.0.post111.tar.gz: PASSED
Checking dist/rapidyaml-python-0.2.0.post111.zip: PASSED
Uploading distributions to https://test.pypi.org/legacy/
  dist/rapidyaml-python-0.2.0.post111-cp37-cp37m-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl (140.5 KB)
  dist/rapidyaml-python-0.2.0.post111-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (134.0 KB)
  dist/rapidyaml-python-0.2.0.post111-cp37-cp37m-win_amd64.whl (151.3 KB)
  dist/rapidyaml-python-0.2.0.post111-cp38-cp38-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl (140.8 KB)
  dist/rapidyaml-python-0.2.0.post111-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (134.1 KB)
  dist/rapidyaml-python-0.2.0.post111-cp38-cp38-win_amd64.whl (151.2 KB)
  dist/rapidyaml-python-0.2.0.post111-cp39-cp39-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl (140.5 KB)
  dist/rapidyaml-python-0.2.0.post111-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (134.1 KB)
  dist/rapidyaml-python-0.2.0.post111-cp39-cp39-win_amd64.whl (151.4 KB)
  dist/rapidyaml-python-0.2.0.post111.tar.gz (706.7 KB)
  dist/rapidyaml-python-0.2.0.post111.zip (823.5 KB)
username set by command options
password set by command options
username: __token__
password: <hidden>
Uploading rapidyaml-python-0.2.0.post111-cp37-cp37m-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl

  0%|          | 0.00/184k [00:00<?, ?B/s]
100%|██████████| 184k/184k [00:01<00:00, 103kB/s]
Content received from server:
<html>
 <head>
  <title>400 Binary wheel 'rapidyaml-python-0.2.0.post111-cp37-cp37m-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl' has an unsupported platform tag 'cp37-cp37m-manylinux_2_5_i686'.</title>
 </head>
 <body>
  <h1>400 Binary wheel 'rapidyaml-python-0.2.0.post111-cp37-cp37m-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl' has an unsupported platform tag 'cp37-cp37m-manylinux_2_5_i686'.</h1>
  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>
Binary wheel &#x27;rapidyaml-python-0.2.0.post111-cp37-cp37m-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl&#x27; has an unsupported platform tag &#x27;cp37-cp37m-manylinux_2_5_i686&#x27;.


 </body>
</html>
HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
Binary wheel 'rapidyaml-python-0.2.0.post111-cp37-cp37m-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl' has an unsupported platform tag 'cp37-cp37m-manylinux_2_5_i686'.
```
Do you know what's causing this?
