### DISCUSSION TITLE
musllinux options

### DISCUSSION THREAD

**Discussion by MrBitBucket** [pypa/cibuildwheel#936] [General]
Is it possible to specify explicit build options for the musl builds? I have tried to build reportlab musllinux, but it seems that we need to install a few packages there to make things work properly. In my alpine vm I need to do something like

. I tried the docker for musil eg 

to get a wheel built, installed and tested. 

I have this

CIBW_BEFORE_BUILD_LINUX: sh -c 'yum install cairo-devel fribidi -y || true'

but I am pretty unclear what the build environment is for musl using

 docker run -it 'quay.io/pypa/musllinux_1_1_x86_64:2021-09-19-a5ef179' /bin/ash

and it doesn't have yum, but my apk commands work fine. So I guess I'm asking if I can use options with names like

CIBW_BEFORE_BUILD_MANYLINUX or CIBW_BEFORE_BUILD_MUSLLINUX?

**Comment by henryiii** [comment]
Please see overrides. They were added at the same time as musllinux for this purpose. (Also they are helpful in other cases, like if you mix manylinux_2_24 with any older manylinux, since that's apt and yum, respectively.)

**Reply by henryiii** [reply]
Example [from the docs](https://cibuildwheel.readthedocs.io/en/stable/options/#examples) is for musllinux specifically. Something like this:

```toml
[tool.cibuildwheel.linux]
before-all = "yum install cairo-devel fribidi -y"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = "apk add cairo-devel fribidi -y"
```

Keep in mind, Alpine has broken compatibility with the `musllinux` standard in version 3.14 by applying a patch not added to CPython (#934). Until they fix that, it's probably a low priority to support them.
