### DISCUSSION TITLE
Globbing in environment-pass

### DISCUSSION THREAD

**Discussion by henryiii** [pypa/cibuildwheel#941] [Ideas]
The current environment-pass is a strict solution, selecting just what you want one at a time. We avoided the more general "pass everything" idea. Just a thought, what about allowing globbing in environment options - maybe we can get the best of both worlds? It would look like this:

```toml
environment-pass = "PIP_*"
# All environment variables that start with PIP_ are passed
environment-pass = "*"
# All environment variables are passed (see below for exceptions)
```

For globbing, a few "PATH" variables (either an explicitly listed set, or possibly anything that ends in PATH) would be ignored due to potential bad side effects - they would have to be listed explicitly without globbing to match. (Or this could be based on contents looking like host paths, etc.) We could support the same expansion used for selectors here. The presences of `?*[{` would activate globbing.
