### DISCUSSION TITLE
Rust build fails on ubuntu aarch64

### DISCUSSION THREAD

**Discussion by RobertCraigie** [pypa/cibuildwheel#957] [Q&A]
https://github.com/RobertCraigie/prisma-client-py/runs/4497941477?check_suite_focus=true

Relevant part of the actions workflow:
```yml
jobs:
  build-query-engine:
    name: Build Query Engine py3${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["6", "7", "8", "9", "10"]
        os: [ubuntu-20.04, windows-2019, macos-10.15]
    env:
      # TODO: run tests on the built wheels
      CIBW_BUILD: "cp3${{ matrix.python-version }}-*"
      CIBW_BUILD_VERBOSITY: 1
      CIBW_BEFORE_ALL_LINUX: "curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y && yum install -y openssl-devel"
      CIBW_BEFORE_BUILD_LINUX: "pip3 install --upgrade keyrings.alt"
      CIBW_ARCHS_LINUX: "auto aarch64"
      CIBW_ENVIRONMENT: 'PATH="$PATH:$HOME/.cargo/bin"'
      CIBW_SKIP: "cp27-* cp34-* cp35-* pp* *-win32"

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Setup env
        run: |
          python -m pip install --upgrade wheel setuptools maturin

      - if: runner.os == 'Linux'
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64

      - name: Install cibuildwheel
        run: |
          python -m pip install -U cibuildwheel==2.3.0
      - name: Build wheels
        working-directory: src/query-engine
        run: |
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          path: ./src/query-engine/wheelhouse/*.whl
```

Error:
> 💥 maturin failed
Caused by: Cargo metadata failed. Does your crate compile with cargo build?
Caused by: cargo metadata exited with an error: Updating crates.io index
Updating git repository https://github.com/prisma/prisma-engines
Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/tmp/pip-modern-metadata-lp697kh4', '--interpreter', '/opt/python/cp310-cp310/bin/python']' returned non-zero exit status 1.

This build succeeds on all other platforms and architectures currently being used.

The package can also be installed locally: https://github.com/PyO3/maturin/discussions/743#discussioncomment-1793569

I do not know if this issue has anything to do with cibuildwheel but any help would be greatly appreciated :)
