### ISSUE TITLE
Unable to build wheels for Python 3.10

### ISSUE THREAD

**Issue by severinsimmler** [pypa/cibuildwheel#1001]
### Description

I'm trying to build wheels for Python 3.10, but it fails with this error:

```
Building cp310-manylinux_x86_64 wheel
CPython 3.10 manylinux x86_64

Setting up build environment...
  
      + /opt/python/cp38-cp38/bin/python -c 'import sys, json, os; json.dump(os.environ.copy(), sys.stdout)'
      + which python
  cibuildwheel: python available on PATH doesn't match our installed instance. If you have modified PATH, ensure that you don't overwrite cibuildwheel's entry or insert python above it.
```

### Build log

https://github.com/severinsimmler/chaine/runs/4954706486?check_suite_focus=true

### CI config

https://github.com/severinsimmler/chaine/blob/master/.github/workflows/main.yml

**Comment by Czaki** [comment]
`manylinux1` is shipped with python up to 3.9 https://github.com/pypa/manylinux/tree/manylinux1. `manylinux1` reaches the end of life on 1 of January. Based on documentation, to build python3.10 wheels you need to use at least `manylinux2010`

**Comment by henryiii** [comment]
Yep. I'd recommend dropping Python 3.6 & manylinux1 at the same time, as that's the main reason to have manylinux1. There are a few old pips for 3.7 and even 3.8 (even though it's supposed to not be supported), but most pips too old to read manylinux 2010 are from 3.6.

There's also no point even today producing a Python 3.9 wheel via manylinux1. If you do want to base the manylinux version on the Python version, you can use an override. Personally, I'd use this in pyproject.toml:

```toml
[tool.cibuildwheel]
test-extras = "test"
test-command = "pytest {project}/tests"
manylinux-x86_64-image = "manylinux2014"
manylinux-i686-image = "manylinux2014"

# Before Python 3.10, manylinux2010 is the most compatible
[[tool.cibuildwheel.overrides]]
select = "cp3?-*"
manylinux-x86_64-image = "manylinux2010"
manylinux-i686-image = "manylinux2010"
```
