### ISSUE TITLE
Feature Request: Arch aliases

### ISSUE THREAD

**Issue by drewcassidy** [pypa/cibuildwheel#1085]
### Description

Using the platform-specific architecture names as it currently stands causes a lot of headaches when using build matrixes.

for example, my GitHub Actions workflow where I want to run arm builds on their own job:
```yaml
      matrix:
        os: [ macos-11, windows-latest, ubuntu-latest ]
        arch: [ ['x86', 'x86_64', 'AMD64', 'x86_64' ] ] #[suffix, mac, windows, linux] arch names
        include:
          - os: ubuntu-latest
            arch: [ 'ARM', 'arm64', 'arm64', 'aarch64' ]
```

 It would be nice if cibuildwheel would be able to handle `x86_64` on windows and `arm64` on linux so that a single key can be used across all platforms
