### ISSUE TITLE
Is there a way to use parallelism when building the wheels?

### ISSUE THREAD

**Issue by Strilanc** [pypa/cibuildwheel#1088]
Waiting for cibuildwheel to finish is *really* painful, even for a single wheel. Is there a flag I can use in order to force it to use multiple threads when building? For example, when building code with `make` I can specify `--jobs 8` to build 8 source files at a time instead of 1 at a time.

For scale, cibuildwheel is one hundred (!!!!!) times slower than all the other checks I do. Being able to reduce that to 10x slower by using parallelism would be hugely helpful.

**Comment by dvarrazzo** [comment]
You can use the github action grid, or some equivalent feature in the CI system you use.

I have done it recently [on setproctitle](https://github.com/dvarrazzo/py-setproctitle/blob/master/.github/workflows/packages.yml) and build went down from hours to 10 minutes.

The result is [some 30 parallel jobs](https://github.com/dvarrazzo/py-setproctitle/actions/runs/2170114677).

**Comment by henryiii** [comment]
CI runners have at most 2 cores on most CI's, and run on shared resources. So that's 6x slower than local, or the equivalent of 6 minutes local time. Plus cibuildwheel is downloading Python and setting up multiple virtual environments, downloading dependencies, etc - easily can be the remaining up to 4 minutes. So that sounds perfectly reasonable. Your build should be using both available cores as long as you've set it up to do that. Cibuildwheel in parallel would not give you much at all. Though I guess you could do it yourself with `CIBW_BUILD=<first half> cibuildwheel & ; CIBW_BUILD=<second half> cibuildwheel2` followed by a wait for the last two launched background jobs. See https://stackoverflow.com/questions/356100/how-to-wait-in-bash-for-several-subprocesses-to-finish-and-return-exit-code-0. I don't think it will be much faster, though.

**Comment by Strilanc** [comment]
If you actually look at what is taking time, it is not downloading dependencies or running tests. In one of my "fast" cases, the setup and teardown takes about a minute and the tests also take about a minute. Which leaves 8 minutes of building:

![image](https://user-images.githubusercontent.com/79941/167748401-656a8b41-d8d8-485c-8573-c04ebb94d6bd.png)

I already am only doing one wheel build per worker, so I'll get no benefit from two invocations. What I need is for cibuildwheel to use two cores for one build, so that it is not processing one C++ file at a time.

I did realize that my worse offenders are actually building numpy and pandas, in addition to my wheel, which is why they take like 40 minutes instead of 10-20. The actual time spent building my wheel is 12.5 minutes. Maybe I should go poke numpy and pandas to have wheels for `cp39-manylinux_i686`, or decide to stop supporting it myself.

**Comment by henryiii** [comment]
At least numpy and pandas do build in parallel. Setuptools doesn't directly support it (unless you have multiple extensions), but it's easy to patch in, pybind11 and numpy both have utilities for it (and of course CMake via Scikit-build, etc. all support it). As long as you are doing that, you aren't waisting that much time not running cibuildwheel in two threads.

Yes, if you provide wheels for something your dependencies don't, not sure it's very helpful. Users will have to build numpy & pandas to use your packaged binary. Also make sure you are using the same manylinux family they are using or better. (like manylinux2014 for Python 3.10, which we do default to these days). If you go older, you'll have to build them if you use them.

**Comment by joerick** [comment]
I don't think currently that it makes sense to provide build parallelism within cibuildwheel. There are already options to do it at a lower level (compiler flags) or at a higher level (CI build matrices). Adding it in cibuildwheel is probably not going to be worth the complexity.

**Comment by joerick** [comment]
One thing that potentially could improve build performance would be to be a bit cleverer about the network IO. E.g. we could download the next docker image or Python version while the previous build is running. That might save a little time. But again, would it be worth the added complexity? Not sure...

**Comment by ddelange** [comment]
I like the high level (CI build matrices) solution, I can split out arch and linux flavour like below. But since QEMU is painfully slow for aarch64, cibuildwheel runs a bunch of tests on the wheels after building, the wait for aarch64 to finish on the below concurrency 2 is still resulting in hours of CI.

Solution is to additionally split out python versions. I would however prefer not to hardcode python versions in CI, rather to let the cibuildwheel `python_requires='>=3.6'` mechanics determine which wheels to build.

Maybe there is a neat way of introducing the possibility for further concurrency other than implementing parallellism inside cibuildwheel? Most runners only have 2 CPU cores anyway so that would not give a huge speedup...

```yaml
# gh actions
jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - {os: ubuntu-latest, arch: x86_64, build: "*manylinux*"}
          - {os: ubuntu-latest, arch: x86_64, build: "*musllinux*"}
          - {os: ubuntu-latest, arch: aarch64, build: "*manylinux*"}
          - {os: ubuntu-latest, arch: aarch64, build: "*musllinux*"}
          - {os: macos-latest, arch: x86_64, build: "*"}
          - {os: macos-latest, arch: arm64, build: "*"}
          - {os: windows-latest, arch: AMD64, build: "*"}
          - {os: windows-latest, arch: x86, build: "*"}
    steps:
      - uses: docker/setup-qemu-action@v2
        if: runner.os == 'Linux'
      - uses: pypa/cibuildwheel@v2.10.0
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BUILD: ${{ matrix.build }}
```
