### ISSUE TITLE
Proper config for building from sdist using github action

### ISSUE THREAD

**Issue by ajfriend** [pypa/cibuildwheel#1125]
### Description

Hi. I'm trying to use the feature added in #1096 to build from SDists using the `pypa/cibuildwheel` GitHub Action.

I'm currently working on it in this PR: https://github.com/uber/h3-py/pull/258

## Main question (tests currently not working)

What's the idiomatic/correct way to set up the `CIBW_TEST_COMMAND` variable when building from the SDist?

[Neither of the following seem to work](https://github.com/uber/h3-py/pull/258/commits/ce354cd92c48d81844f8df6d9ab8fd67026280ee):

```
CIBW_TEST_COMMAND: pytest {project}/tests
CIBW_TEST_COMMAND: pytest h3-py/tests
```

I'm assuming that's because the `{project}` variable is set differently for the SDist case.

## Minor idiom question

I'm building the SDist in a separate GA job, and downloading the artifact for the CIBW job. Does anyone see a cleaner/safer way than the glob pattern to specify the SDist?

```
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/cibuildwheel@v2.6.0
        with:
          package-dir: dist/h3-*.tar.gz
          output-dir: dist
```
