### ISSUE TITLE
Support multiple manylinux versions in configuration

### ISSUE THREAD

**Issue by EwoutH** [pypa/cibuildwheel#1153]
For some projects it's useful to build multiple manylinux builds for the same Python version, to offer the latest glibc features and performance that a platform supports. It would be very nice if cibuildwheel would support that natively, by for example taking a list of  manylinux images as a valid input parameter. For example (using `pyproject.toml`):
```toml
[tool.cibuildwheel]
manylinux-x86_64-image = ["manylinux2014", "manylinux_2_24", "manylinux_2_28"]
```
