### ISSUE TITLE
3.11 builds failing with v2.8.1 on manylinux2010 images

### ISSUE THREAD

**Issue by godlygeek** [pypa/cibuildwheel#1187]
### Description

With:
```yaml
        cibw_python: [ "cp37-*", "cp38-*", "cp39-*", "cp310-*", "cp311-*"]
```
and
```yaml
        env:
          CIBW_PRERELEASE_PYTHONS: True
```

I'm seeing this error:
```
Setting up build environment...
  
      + /opt/python/cp38-cp38/bin/python -c 'import sys, json, os; json.dump(os.environ.copy(), sys.stdout)'
      + which python
  cibuildwheel: python available on PATH doesn't match our installed instance. If you have modified PATH, ensure that you don't overwrite cibuildwheel's entry or insert python above it.
  Error: Process completed with exit code 1.
```

This didn't occur with 2.8.0 - I suspect it's somehow related to this changelog entry:

> 🛠 The GitHub Action will ensure a compatible version of Python is installed on the runner (#1114)

I'm also seeing
```
Run actions/setup-python@v4
  with:
    python-version: 3.7 - 3.10
    update-environment: false
    token: ***
  env:
    CIBW_BUILD: cp311-*
    CIBW_ARCHS_LINUX: x86_64
    CIBW_MANYLINUX_X86_64_IMAGE: manylinux[20](https://github.com/bloomberg/memray/runs/7420878603?check_suite_focus=true#step:3:21)10
    CIBW_MANYLINUX_I686_IMAGE: manylinux2010
    CIBW_PRERELEASE_PYTHONS: true
    CIBW_TEST_EXTRAS: test
    CIBW_TEST_COMMAND: pytest {package}/tests
```
in the build log - perhaps that "python-version: 3.7 - 3.10" is the problem?

### Build log

https://github.com/bloomberg/memray/runs/7421778954?check_suite_focus=true

### CI config

https://github.com/bloomberg/memray/blob/f9bfaacea95c9c565189da2eeb121a3303c11c71/.github/workflows/build_wheels.yml
