### ISSUE TITLE
`.gitlab-ci.yml` failing as published (

### ISSUE THREAD

**Issue by David00** [pypa/cibuildwheel#1269]
### Description

Hello,

I'm trying to run a CI job using `cibuildwheel` on my private Gitlab server.  The pipeline fails due to a DNS lookup error when trying to resolve `docker`.  My `.gitlab-ci.yml` file matches verbatim what is shown in the [cibuildwheel documentation for using Gitlab CI](https://cibuildwheel.readthedocs.io/en/stable/setup/#gitlab-ci): 

```.gitlab-ci.yml
linux:
  image: python:3.8
  # make a docker daemon available for cibuildwheel to use
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
  script:
    - curl -sSL https://get.docker.com/ | sh
    - python -m pip install cibuildwheel==2.10.0
    - cibuildwheel --output-dir wheelhouse
  artifacts:
    paths:
      - wheelhouse/
```

I was running Gitlab CE version 14.7 and a single runner (arm64, Raspberry Pi OS Lite):
```
$ gitlab-runner -v
Version:      15.2.1
Git revision: 32fc1585
Git branch:   15-2-stable
GO version:   go1.17.9
Built:        2022-07-26T21:21:20+0000
OS/Arch:      linux/arm64
```

And I saw the Gitlab Runner troubleshooting docs that say the runner and the Gitlab server should be on the same version.  So, I upgraded my Gitlab server to 15.3.3 and setup a new runner on a new Ubuntu server in my LAN.  The new runner is: 

```
$ gitlab-runner -v
Version:      15.3.0
Git revision: bbcb5aba
Git branch:   15-3-stable
GO version:   go1.17.9
Built:        2022-08-19T22:41:11+0000
OS/Arch:      linux/amd64
```

Both runners have identical configs, and both fail with the same issue.  Here is the runner config on the 15.3.0 amd64 runner:

```toml
concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "dev-vm"
  url = "http://192.168.10.120/"
  id = 2
  token = "myTokenHere"
  token_obtained_at = 2022-09-14T23:55:07Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
```

Here is the full build log from the pipeline job.
[build-log.txt](https://github.com/pypa/cibuildwheel/files/9570750/build-log.txt)

I've tried changing `docker` in `tcp://docker` to `localhost` and `172.17.0.1` (the IP address of my docker0 interface). Both of these fail with the message: 
> Cannot connect to the Docker daemon at tcp://<IP address or localhost from above>:2375/. Is the docker daemon running?

Thanks,
David

### CI config

https://cibuildwheel.readthedocs.io/en/stable/setup/#gitlab-ci
