### ISSUE TITLE
OSX arm64 produced wheel is actually x86_64

### ISSUE THREAD

**Issue by ixje** [pypa/cibuildwheel#1345]
### Description

**Preface**
I used to build windows, linux and osx wheels using Github with a strategy matrix and `os: [ubuntu-20.04, macos-11, windows-2019]
` together with
```
uses: pypa/cibuildwheel@v2.8.1
        env:
            CIBW_BEFORE_BUILD_LINUX: "python3 -m pip install cmake"
            CIBW_BUILD: "cp310-macosx_x86_64 cp310-win_amd64 cp310-manylinux_x86_64"
```
everything worked fine. 

**The issue**
Today I was asked to add OSX M1 support. At first I only added `cp310-macosx_arm64` to `CIBW_BUILD` and updated cibuildwheel to `2.11.2`. That didn't produce any arm wheels. Digging a bit in the documentation I found
> Apple Silicon wheels are not built by default on Intel runners, but can be enabled by adding extra archs to the [CIBW_ARCHS_MACOS option](https://cibuildwheel.readthedocs.io/en/stable/options/#archs) - e.g. x86_64 arm64. Cross-compilation is provided by the Xcode toolchain.

Attempt 2 after adding `CIBW_ARCH_MACOS` as per docs
```
uses: pypa/cibuildwheel@v2.11.2
        env:
            CIBW_BEFORE_BUILD_LINUX: "python3 -m pip install cmake"
            CIBW_ARCHS_MACOS: "x86_64 arm64"
            CIBW_BUILD: "cp310-macosx_x86_64 cp310-macosx_arm64 cp310-win_amd64 cp310-manylinux_x86_64"
```
resulted in 
```
2 wheels produced in 2 minutes:
  pybiginteger-1.2.7-cp310-cp310-macosx_10_9_x86_64.whl   128 kB
  pybiginteger-1.2.7-cp310-cp310-macosx_11_0_arm64.whl    128 kB
```
So far so good. Handed the arm version to a user who installed the wheel successfully. Once he tried to import the module he reported this back
```
>>> from pybiginteger import BigInteger
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/tyleradams/venv/lib/python3.10/site-packages/pybiginteger.cpython-310-darwin.so, 0x0002): tried: '/Users/tyleradams/venv/lib/python3.10/site-packages/pybiginteger.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```

It looks quite similar to https://github.com/pypa/cibuildwheel/issues/1278 except that issue is believed to be Python 3.8 specific, whereas this happens for 3.10. 

### Build log

https://github.com/CityOfZion/BigIntegerCpp/actions/runs/3514975488/jobs/5889678624

### CI config

https://github.com/CityOfZion/BigIntegerCpp/blob/a026a40cc20fd65610225e1abd110c8ae0210ae6/.github/workflows/build-python.yml#L20
