### ISSUE TITLE
[Feature Request] Add major versioned  tag or branch for GitHub Action

### ISSUE THREAD

**Issue by XuehaiPan** [pypa/cibuildwheel#1358]
### Description

The `cibuildwheel` repo contains a [`action.yml`](https://github.com/pypa/cibuildwheel/blob/main/action.yml), which can be used in GitHub Action:

https://github.com/pypa/cibuildwheel/blob/9c6416d4ac4cf88b867c2993e1b0c4a014000fa0/examples/github-minimal.yml#L16-L24

However, users need to bump the tag version in workflow files each time a new version of `cibuildwheel` is released.

Is there any plan to have a major versioned tag or branch? For example:

- [actions/setup-python](https://github.com/actions/setup-python) uses major versioned tags <https://github.com/actions/setup-python/tags>. Users can use the following:

```yaml
- name: Setup Python
  uses: actions/setup-python@v4
```

to get the latest `v4` workflows.

- [pypa/gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish) uses major versioned branches <https://github.com/pypa/gh-action-pypi-publish/branches>. Users can use the following:

```yaml
- name: Publish a Python distribution to PyPI
  uses: pypa/gh-action-pypi-publish@release/v1
  with:
    user: __token__
    password: ${{ secrets.PYPI_API_TOKEN }}
```

to get the latest `v1` workflows.
