### ISSUE TITLE
[Question] cibw cannot find pybind11 even though it's set to be installed via `CIBW_BEFORE_ALL` option

### ISSUE THREAD

**Issue by tddschn** [pypa/cibuildwheel#1393]
Here's my GitHub Actions job to build wheel for a Python module with C++ code, (bound using the `pybind11` module):

```yaml

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          python -m pip install pybind11 cibuildwheel
      - name: Build wheels
        # uses: pypa/cibuildwheel@v2.8.1
        run: |
          cibuildwheel
```

Related configuration in `pyproject.toml`:

```toml
[tool.cibuildwheel]
# before-build = "pip install pybind11"
before-all = "pip install pybind11" # <--------
test-requires = "pytest"
test-command = "pytest"
```

And it failed with error `ModuleNotFoundError: No module named 'pybind11'`, even though it's set to be installed via `CIBW_BEFORE_ALL` option, can you help me figure out why? Thank you in advance.

I read the documentation on [`CIBW_BEFORE_ALL`](https://cibuildwheel.readthedocs.io/en/latest/options/#before-all), it says the option `Execute a shell command on the build system before any wheels are built`, so I supposed that it should do the job.

I have included links to the job run's output, the full workflow file, and my setup.py file for reference. I am also including the commands I use to build and run locally.

Any help would be greatly appreciated.

<details>
  <summary>Additional info</summary>
  
[Link to the job run's output](https://github.com/easy-graph/Easy-Graph/actions/runs/3867354850/jobs/6592072102)  
[Link to the full workflow file](https://github.com/easy-graph/Easy-Graph/blob/2d702844a4e86538cce5786288c7197e998e698a/.github/workflows/release-cibuildwheel.yaml#L51)  
[Link to `setup.py`](https://github.com/easy-graph/Easy-Graph/blob/2d702844a4e86538cce5786288c7197e998e698a/setup.py#L8)

Commands to build and run locally:

```bash
    git clone https://github.com/easy-graph/Easy-Graph && cd Easy-Graph && git checkout pybind11
    pip install pybind11
    python3 setup.py install
```

</details>
