### ISSUE TITLE
Pip install a specific version of package in `CIBW_BEFORE_BUILD`

### ISSUE THREAD

**Issue by oooo26** [pypa/cibuildwheel#1396]
### Description

Hi, I am trying to set `CIBW_BEFORE_BUILD: "pip install scipy<=1.9.1"` in the Github Action. And it comes to
```bash
  + pip install scipy<=1.9.1

  The system cannot find the file specified.
  Error: Command pip install scipy<=1.9.1 failed with code 1. None
```

Is there any method to add the version limit to `CIBW_BEFORE_BUILD`? 
Thanks for helping!

**Comment by oooo26** [comment]
And here is a minimum example:
```yaml
name: test

on:
  workflow_dispatch:

jobs:
  Start:
    name: Wheels on windows-latest
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels for Windows
        uses: pypa/cibuildwheel@v2.11.3
        env:
          CIBW_SKIP: "pp*"
          CIBW_BEFORE_BUILD: "pip install scipy<=1.9.1"

      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash
```
