### ISSUE TITLE
Allow setting target-platform-dependent environment variables

### ISSUE THREAD

**Issue by phoerious** [pypa/cibuildwheel#1426]
### Description

I am cross-compiling native modules for `CIBW_ARCHS_MACOS="x86_64 arm64"` and my module requires external native libraries, which are installed to

- `/usr/local/share/vcpkg/installed/x64-osx/{include,lib}`
- `/usr/local/share/vcpkg/installed/arm64-osx/{include,lib}`

Now I need to tell the compiler which of these two to use, but when I set `LIBRARY_PATH=/usr/local/share/vcpkg/installed/x64-osx/lib:/usr/local/share/vcpkg/installed/arm64-osx/lib`, the result is missing libraries in the arm64 wheel, because the compiler and delocate-wheel find the required libraries in the `x64` folder and simply ignore them, because they have the wrong architecture. If I swap the paths, the ARM64 builds work, but now the Intel builds have this issue.

I tried messing with `CIBW_ENVIRONMENT_MACOS`, but the `_PYTHON_HOST_PLATFORM` and `ARCHFLAGS` aren't set yet when this code is executed and the Bash lexer also chokes on more complex commands containing pipes. I can access the variables in `CIBW_BEFORE_BUILD_MACOS`, but whatever I do there doesn't carry over to the actual build and repair commands.

My current "solution" is:

1. Check in `setup.py` if `CIBUILDWHEEL` is set and add the correct include and library paths to the compiler command.
2. Add this to the GitHub runner definition:
    ```yaml
    CIBW_REPAIR_WHEEL_COMMAND_MACOS: >-
      DYLD_LIBRARY_PATH=$LIBRARY_PATH_{delocate_archs} delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}
    
    CIBW_ENVIRONMENT_MACOS: >-
      LIBRARY_PATH_x86_64="/usr/local/share/vcpkg/installed/x64-osx/lib"
      LIBRARY_PATH_arm64="/usr/local/share/vcpkg/installed/arm64-osx/lib"
    ```

This is an extremely ugly solution, because it is very redundant and it requires me to hard-code deployment information in my `setup.py`.

I would highly appreciate a proper solution for setting environment variables depending on the wheel target architecture.

**Comment by joerick** [comment]
I believe (if I'm reading this right) that a more elegant solution to this would be possible through [TOML overrides](https://cibuildwheel.readthedocs.io/en/stable/options/#overrides). You can do something like:

_pyproject.toml_
```toml
[tool.cibuildwheel]
# Normal options, etc.

[[tool.cibuildwheel.overrides]]
select = "*-macosx_x86_64"
environment = { LIBRARY_PATH="/usr/local/share/vcpkg/installed/x64-osx/lib" }

[[tool.cibuildwheel.overrides]]
select = "*-macosx_arm64"
environment = { LIBRARY_PATH="/usr/local/share/vcpkg/installed/arm64-osx/lib" }
```
