### ISSUE TITLE
Allow access to working directory when building wheel from an sdist

### ISSUE THREAD

**Issue by mroeschke** [pypa/cibuildwheel#1492]
### Description

I am building an sdist from a repository that also has helper scripts that I want to use in `pypa/cibuildwheel` GHA. I do not necessarily want to include these helper scripts in the sdist though.

```yaml
# Github Actions
build_wheel:
    steps:
      # Contains helper scripts for pypa/cibuildwheel
      - uses: actions/checkout@v3

      - name: Download sdist
        uses: actions/download-artifact@v3
        with:
          name: sdist
          path: ./dist

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.3
        with:
          package-dir: ./dist/sdist_path.tar.gz
``` 

```toml
# pyproject.toml
[tool.cibuildwheel]
test-command = "python repo/helper/test_wheel.py"
```

In this example, I don't want to package `repo/helper` in the sdist, but it would be nice to have access to it for `test-command`.  Is there a workaround I am missing?
