### ISSUE TITLE
Add examples in docs about setting "per-platform" `before-build` options in `pyproject.toml`

### ISSUE THREAD

**Issue by thejcannon** [pypa/cibuildwheel#1578]
### Description

:wave: Loving using this. Thanks y'all!

One thing I hit:

https://cibuildwheel.readthedocs.io/en/stable/options/#before-build lists "per-platform" env vars (e.g. `CIBW_BEFORE_BUILD_MACOS`), but trying:

```toml
[tool.cibuildwheel]
before-build-macos = "..."
```

I get
```
cibuildwheel.options.ConfigOptionError: "Option 'before-build-macos' not supported in a config file. Perhaps you meant 'before-build'?"
```

**Comment by henryiii** [comment]
Either:

```toml
[tool.cibuildwheel.macos]
before-build = "..."
```

Or:

```toml
[tool.cibuildwheel]
macos.before-build = "..."
```

(Just two ways of writing the same thing in TOML).

With the newer overrides system, you could also mimic it:

```toml
[[tool.cibuildwheel.overrides]]
select = "*-macosx_*"
before-build = "..."
```
