### ISSUE TITLE
Cannot find or install `meson-python` to build fortran sources

### ISSUE THREAD

**Issue by brmather** [pypa/cibuildwheel#1673]
### Description

Every time I want to build a wheel and compile fortran sources using meson I get the following error complaining that actions can't find `meson-python`:

```
  ERROR: Could not find a version that satisfies the requirement meson-python (from versions: none)
  ERROR: No matching distribution found for meson-python
```

I've tried many different incarnations, including installing ninja and meson to the system directory before using cibuildwheels, but my actions always fail. Any help would be greatly appreciated!

My GitHub actions workflow looks like this:

```yaml
name: Build wheels

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BEFORE_BUILD_LINUX: "pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple numpy meson-python ninja setuptools build"
          CIBW_BEFORE_BUILD_WINDOWS: "pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple numpy meson-python ninja setuptools build"
          CIBW_BEFORE_BUILD_MACOS: "pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple numpy meson-python ninja setuptools build"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz
```

### Build log

https://github.com/underworldcode/stripy/actions/runs/6963415288/job/18948952162?pr=109

### CI config

https://github.com/underworldcode/stripy/blob/c5bef9f944e25283bea647b876e662f41ee573e9/.github/workflows/pypi.yml
