### ISSUE TITLE
`can't find rust compiler` when building with Github CI and ubuntu-latest

### ISSUE THREAD

**Issue by aukselis-c1connections** [pypa/cibuildwheel#1684]
### Description

I am building wheels for Python package that uses rust libraries. During the build process rust libraries need to be compiled. When the build procedure is running windows, the build works without an issue. However, if Linux is used the build fails with:
```
        creating build
        creating build/lib.linux-x86_64-cpython-39
        creating build/lib.linux-x86_64-cpython-39/counters
        copying src/counters/astm.rs -> build/lib.linux-x86_64-cpython-39/counters
        creating build/lib.linux-x86_64-cpython-39/fatigue
        copying src/fatigue/fatigue.rs -> build/lib.linux-x86_64-cpython-39/fatigue
        running build_ext
        running build_rust
        error: can't find Rust compiler
```

The CI configuration:

```
name: Build

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest]
    env:
      CIBW_BEFORE_BUILD_LINUX: curl -sSf https://sh.rustup.rs | sh -s -- -y && source "$HOME/.cargo/env"
    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3
      
      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

```

I tried installing compiler on the build container with:
```
CIBW_BEFORE_BUILD_LINUX: curl -sSf https://sh.rustup.rs | sh -s -- -y && source "$HOME/.cargo/env"
```
with no effect

### Build log

https://appp.me/dqO4fK

### CI config

https://appp.me/3cqrnR
