### ISSUE TITLE
Note about `actions/upload-artifact@v4`

### ISSUE THREAD

**Issue by LecrisUT** [pypa/cibuildwheel#1699]
Uploading to the same `dist` artifact is no longer supported [^1]. The documentation would need to be updated accordingly

[^1]: https://github.com/actions/upload-artifact/tree/v4#not-uploading-to-the-same-artifact

**Comment by henryiii** [comment]
Ouch, that affects a lot of things. The ability to simply aggregate was very useful. Is there a nice way to recombine artifacts? If you get all artifacts, you might get things you don't need, and they go into directories. I think the aggregation job will now require at least an extra step.

I'm surprised a very useful feature was axed but no clear replacement was worked out first.

**Comment by LecrisUT** [comment]
Agreed, I did not find a clean way other than sticking to `v3` or downloading all and using the artifact name to merge it back.

I didn't check the git blame to see the discussion on when this was removed, but there was this old issue I stumbled upon: https://github.com/actions/upload-artifact/issues/24

**Comment by Czaki** [comment]
It will be a big pain. In many projects, logs are combined into a single target to simplify download.

**Comment by henryiii** [comment]
If there was just something like "combine: true" (and ideally a way to list artifacts, like in https://github.com/actions/download-artifact/pull/202, possibly even with globs!), then this would be much easier, and the promise of faster downloads is nice. But currently it seems really ugly to workaround for projects like cibuildwheel users (and logging, etc).

**Comment by LecrisUT** [comment]
Download wise, there is an approach by not specifying the `name` in `download-artifact` [^1], which will extract them in their corresponding `name` directory. It is not ideal because it will download all artifacts instead of allowing for a glob pattern.

[^1]: https://github.com/actions/download-artifact/tree/v4#download-all-artifacts

**Comment by henryiii** [comment]
Something like this, perhaps?

```yaml
    - uses: actions/download-artifact@v4
      with:
        path: all

    - run: |
        mkdir dist
        mv all/*/* .
        rmdir all/*
        rmdir all
```

Any way to make that cleaner?

**Comment by LecrisUT** [comment]
Considering that this will most likely be done in a standalone job, that should be ok as being `runs-on: ubuntu-latest`. But I think some sanity paths:
```yaml
    - uses: actions/download-artifact@v4
      with:
        path: all
    - name: Merge files
      run: |
        mkdir dist
        mv all/*/dist/* ./dist
```

The `download-artifact` creates an extra directory between `all` and `dist`

**Comment by henryiii** [comment]
> that should be ok as being `runs-on: ubuntu-latest`

:facepalm:

> The download-artifact creates an extra directory between all and dist

It shouldn't create a `dist` at all. The structure should be `all/<name>/thing.tar.gz`, etc. There is no "dist" (or "wheelhouse", for cibuildwheel) in the archives.

So this should be fine, I think:

```yaml
    - uses: actions/download-artifact@v4
      with:
        path: all

    - name: Merge files
      run: |
        mkdir dist
        mv all/*/* .
```

(all still untested)

**Comment by LecrisUT** [comment]
> It shouldn't create a dist at all. 

This would depend on how you uploaded the artifact `dist/*` vs `dist`. The downloaded artifacts are automatically extracted in those folders. Granted I've only tested the later statement, but the former one has been like that since the beginning, hasn't it?

**Comment by henryiii** [comment]
cibuildwheel artifacts are not in `dist`. They are in `wheelhouse`. So I’m quite sure the directory is already not included by the upload action using the expression we already have.

**Comment by LecrisUT** [comment]
Oh, yes indeed:
```yaml
      - name: Build wheels
        run: pipx run cibuildwheel==2.16.2
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
```
I was remembering these snippets in the documentation:
```yaml
    - name: Build SDist
      run: pipx run build --sdist
    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.tar.gz
...
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist
    - uses: pypa/gh-action-pypi-publish@release/v1
```

**Comment by webknjaz** [comment]
cc @woodruffw — this will affect the secretless publishing recommendations in the PyPI docs, PyPUG and pypi-publish README... FYI

**Comment by webknjaz** [comment]
Just remembered an old unfixed race condition that might've been the inspiration to break things further... https://github.com/actions/toolkit/issues/1235 / https://github.com/actions/download-artifact/issues/140#issuecomment-1314062872

**Comment by woodruffw** [comment]
Yeah, this seems like it'll cause quite a bit of pain for common Python publishing workflows (and maybe other ecosystems as well, like Ruby?)

Has anybody raised this upstream? The actions maintainers have been responsive to unanticipated breakages IME. Apologies if someone already has and I missed it 🙂

**Comment by webknjaz** [comment]
@henryiii @joerick perhaps the docs should show a big scary red banner warning people not to upgrade the affected action?

**Comment by LecrisUT** [comment]
+1 for a big warning banner for the top-level Readme. At the very least if my reading is correct GH Action will raise an error instead of overwriting the old one, so people would probably turn up over here if they are silently effected.

**Comment by henryiii** [comment]
I've successfully shipped cmake with v4 and the changes above:

https://github.com/scikit-build/cmake-python-distributions/pull/438/files

**Comment by LecrisUT** [comment]
Seems like we will have a wrapper for this soon:
https://github.com/re-actors/download-artifact

**Comment by alugowski** [comment]
If `pypi-publish` action supported recursively searching `dist/` then the only change needed would be to name the uploaded artifacts. I opened an issue there: https://github.com/pypa/gh-action-pypi-publish/issues/199

As of today, all that is needed is to name uploaded artifacts:
```yml
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.cibw_archs }}
          path: wheelhouse/*.whl
```

 and then flatten download-action's output:
```yml
      - uses: actions/download-artifact@v4
        with:
          path: dist_artifacts

      - name: Flatten artifacts to dist/
        run: mkdir dist && find dist_artifacts -type f -exec mv {} dist \;
```

**Comment by webknjaz** [comment]
> Seems like we will have a wrapper for this soon:
> https://github.com/re-actors/download-artifact

I'll likely archive it, after all, since the upstream implemented the new `pattern:` input + `merge-multiple: true`. It'll require some manual changes, though. Same with the upload — but this one might benefit from a wrapper. Though, maintaining wrappers would be a pain so I'll see if it'll be worth it.

**Comment by gnikit** [comment]
@alugowski This is pretty much the solution I arrived too, but because I feel uneasy with leaving the `name` field blank, I ended up using `pattern` in the download action, which is marginally better.

```yml
      - uses: actions/upload-artifact@v4
        with:
          name: python-wheels-${{ matrix.os }}-${{ matrix.cibw_archs }}
          path: |
            ./wheelhouse/*.whl
            ./wheelhouse/*.tar.gz
```

```yml
      - uses: actions/download-artifact@v4
        with:
          pattern: python-wheels*
          path: dist
          merge-multiple: true
```

---

Personally, I still don't understand the reasoning behind the complete removal of this core feature in the upload action. Also, I am having a hard time believing the compatibility score from dependabot [![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=actions/upload-artifact&package-manager=github_actions&previous-version=3&new-version=4)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores), 6% failure seems oddly low.
