### ISSUE TITLE
Access environment variables in config-settings

### ISSUE THREAD

**Issue by sarlinpe** [pypa/cibuildwheel#1710]
### Description

It would be handy to set config-settings based on some environment variables, for example when both the build and the `before-all` process need the same arguments, such as here using vcpkg:
```toml
[tool.cibuildwheel.macos]
before-all = "cd dependencies && cmake -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE} && ..."

[tool.cibuildwheel.macos.environment]
VCPKG_INSTALLATION_ROOT = "/Users/runner/work/vcpkg"
CMAKE_TOOLCHAIN_FILE = "${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake"
CMAKE_OSX_ARCHITECTURES = "${CIBW_ARCHS_MACOS}"

[tool.cibuildwheel.macos.config-settings]
"cmake.define.CMAKE_TOOLCHAIN_FILE" = "${CMAKE_TOOLCHAIN_FILE}"
"cmake.define.VCPKG_TARGET_TRIPLET" = "${VCPKG_TARGET_TRIPLET}"
"cmake.define.CMAKE_OSX_ARCHITECTURES" = "${CIBW_ARCHS_MACOS}"
```

Currently this doesn't work. I think that this would require setting `shell=True`:
https://github.com/pypa/cibuildwheel/blob/f11f1b2ef98bf8f855356a62287d50689e5b9e7b/cibuildwheel/util.py#L127

But I'm unsure about potential side effects.
