### ISSUE TITLE
No build identifiers selected, even though build_config is cp312-*

### ISSUE THREAD

**Issue by modem7** [pypa/cibuildwheel#1717]
### Description

I'm having an issue building Python 3.12 wheels on Linux. 

```yaml
cibuildwheel version 2.12.0

Build options:
  platform: linux
  architectures: aarch64, x86_64
  build_selector:
    build_config: cp312-manylinux_*
    skip_config:
    requires_python: >=3.8
    prerelease_pythons: False
  container_engine: docker
  output_dir: /mnt/downloads/cibuildwheel/wheelhouse
  package_dir: /mnt/downloads/cibuildwheel/sdist/borgbackup-1.2.7
  test_selector:
    skip_config:
  before_all: dnf install -y fuse glibc-devel pkgconf-pkg-config libacl-devel libattr-devel libzstd-devel lz4-devel openssl-devel xxhash-devel ncurses-devel && pip install -U pkgconfig pip setuptools setuptools_scm wheel
  before_build:
  before_test:
  build_frontend: pip
  build_verbosity: 0
  config_settings:
  dependency_constraints: pinned
  environment:
  manylinux_images:
    x86_64: quay.io/pypa/manylinux_2_28_x86_64
    i686: quay.io/pypa/manylinux2014_i686:2023-01-14-103cb93
    pypy_x86_64: quay.io/pypa/manylinux2014_x86_64:2023-01-14-103cb93
    aarch64: quay.io/pypa/manylinux_2_28_aarch64
    ppc64le: quay.io/pypa/manylinux2014_ppc64le:2023-01-14-103cb93
    s390x: quay.io/pypa/manylinux2014_s390x:2023-01-14-103cb93
    pypy_aarch64: quay.io/pypa/manylinux2014_aarch64:2023-01-14-103cb93
    pypy_i686: quay.io/pypa/manylinux2014_i686:2023-01-14-103cb93
  musllinux_images:
    x86_64: quay.io/pypa/musllinux_1_1_x86_64:2023-01-14-103cb93
    i686: quay.io/pypa/musllinux_1_1_i686:2023-01-14-103cb93
    aarch64: quay.io/pypa/musllinux_1_1_aarch64:2023-01-14-103cb93
    ppc64le: quay.io/pypa/musllinux_1_1_ppc64le:2023-01-14-103cb93
    s390x: quay.io/pypa/musllinux_1_1_s390x:2023-01-14-103cb93
  repair_command: auditwheel repair -w {dest_dir} {wheel}
  test_command:
  test_extras:
  test_requires:

Cache folder: /home/user/.cache/cibuildwheel

Here we go!

cibuildwheel: No build identifiers selected: BuildSelector(build_config='cp312-manylinux_*', skip_config='', requires_python=<SpecifierSet('>=3.8')>, prerelease_pythons=False)
```

I'm using the following variables:

```bash
export PKGNAME="borgbackup"
export PKGVER=$(grep "${PKGNAME}" requirements.txt | cut -d '=' -f 3 | tr -d '\012\015')
export PKGURL=$(curl -s "https://pypi.org/pypi/${PKGNAME}/${PKGVER}/json" | jq -r '.urls[].url')
export CIBW_BEFORE_ALL='dnf install -y fuse glibc-devel pkgconf-pkg-config libacl-devel libattr-devel libzstd-devel lz4-devel openssl-devel xxhash-devel ncurses-devel && pip install -U pkgconfig pip setuptools setuptools_scm wheel'
export CIBW_MANYLINUX_X86_64_IMAGE='quay.io/pypa/manylinux_2_28_x86_64'
export CIBW_MANYLINUX_AARCH64_IMAGE='quay.io/pypa/manylinux_2_28_aarch64'
export CIBW_ARCHS_LINUX='x86_64 aarch64'
export CIBW_BUILD='cp312-manylinux_*'
```

And the commands to run:
```console
# Download
wget -c $PKGURL -q -O - | tar -xz -C ./sdist/

# Build
cibuildwheel --platform linux --output-dir wheelhouse sdist/$PKGNAME-$PKGVER
```

It seems to work with cp311 but not cp312.

Full script in case anyone needs to replicate:

```bash
#/bin/bash

set -e

# Prerequesites
sudo python3 -m pip install -U build cibuildwheel PyYAML requests
sudo apt install -y jq wget curl

# Variables
export PKGNAME="borgbackup"
export PKGVER=$(grep "${PKGNAME}" requirements.txt | cut -d '=' -f 3 | tr -d '\012\015')
export PKGURL=$(curl -s "https://pypi.org/pypi/${PKGNAME}/${PKGVER}/json" | jq -r '.urls[].url')
export CIBW_BEFORE_ALL='dnf install -y fuse glibc-devel pkgconf-pkg-config libacl-devel libattr-devel libzstd-devel lz4-devel openssl-devel xxhash-devel ncurses-devel && pip install -U pkgconfig pip setuptools setuptools_scm wheel'
export CIBW_MANYLINUX_X86_64_IMAGE='quay.io/pypa/manylinux_2_28_x86_64'
export CIBW_MANYLINUX_AARCH64_IMAGE='quay.io/pypa/manylinux_2_28_aarch64'
export CIBW_ARCHS_LINUX='x86_64 aarch64'
export CIBW_BUILD='cp312-manylinux_*'

# Load Multiarch settings
docker run --rm --privileged tonistiigi/binfmt
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

# Create directories
mkdir -p sdist wheelhouse

# Download
wget -c $PKGURL -q -O - | tar -xz -C ./sdist/

# Build
cibuildwheel --platform linux --output-dir wheelhouse sdist/$PKGNAME-$PKGVER

# Remove working files
rm -rf ./sdist/$PKGNAME*

# Remove leftover Docker images
docker inspect --type=image tonistiigi/binfmt >/dev/null 2>&1 && docker rmi tonistiigi/binfmt || echo 'binfmt image does not exist. Will not delete.'
docker inspect --type=image quay.io/pypa/musllinux_1_1_x86_64 >/dev/null 2>&1 && docker rmi multiarch/qemu-user-static || echo 'qemu-user-static image does not exist. Will not delete.'
docker images | grep quay.io/pypa/ | awk "{print \$3}" >/dev/null 2>&1 && docker rmi $(docker images | grep quay.io/pypa/ | awk "{print \$3}") || echo 'quay.io/pypa image does not exist. Will not delete.'
```
