### ISSUE TITLE
CIBuildWheel can't be used on Linux ARM64 Runners

### ISSUE THREAD

**Issue by Laky-64** [pypa/cibuildwheel#1770]
### Description

I'm trying to use CiBuildWheels on my custom arm64 runner, but I can't build it because setup-python@v5 isn't available on arm64, there is a way to use directly the local python3.12?

### Build log

https://github.com/pytgcalls/ntgcalls/actions/runs/8101636927/job/22144357139

### CI config

https://github.com/pytgcalls/ntgcalls/blob/master/.github/workflows/build.yml

**Comment by henryiii** [comment]
You can use the PyPI package. The action requires setup-python. Since Apple Silicon runners do not have a built-in `python`, it's required to use setup-python there.

**Comment by Laky-64** [comment]
> You can use the PyPI package. The action requires setup-python. Since Apple Silicon runners do not have a built-in `python`, it's required to use setup-python there.

I’m not on macOS, but on a custom runner based on Linux arm64

**Comment by Laky-64** [comment]
@henryiii

**Comment by henryiii** [comment]
I know, I'm just explaining (one of the) reasons we have to use `setup-python` in our action. If you can't use actions like setup-python, you can't use cibuildwheel as an action either. But that's fine, just use the PyPI package, that's all the action does anyway.

**Comment by henryiii** [comment]
For example, if your local `python` has `pipx`, just replace this:

```yaml
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.8"
          CIBW_BUILD: cp3*-${{ matrix.cibw_os_build }}*
          CIBW_SKIP: cp36-* cp37-*
          CIBW_BUILD_VERBOSITY: 3
          CIBW_TEST_SKIP: "*-macosx_arm64 *-manylinux_aarch64"
          CIBW_TEST_COMMAND: python -c "from ntgcalls import NTgCalls; NTgCalls().ping()"
          CIBW_MANYLINUX_AARCH64_IMAGE: ghcr.io/pytgcalls/ntgcalls/arm64:latest
```

with this:

```yaml
      - name: Build wheels
        run: pipx run cibuildwheel==2.16.5
        env:
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.8"
          CIBW_BUILD: cp3*-${{ matrix.cibw_os_build }}*
          CIBW_SKIP: cp36-* cp37-*
          CIBW_BUILD_VERBOSITY: 3
          CIBW_TEST_SKIP: "*-macosx_arm64 *-manylinux_aarch64"
          CIBW_TEST_COMMAND: python -c "from ntgcalls import NTgCalls; NTgCalls().ping()"
          CIBW_MANYLINUX_AARCH64_IMAGE: ghcr.io/pytgcalls/ntgcalls/arm64:latest
```

Also, I recommend using our TOML config instead of lots of static environment variables. Only the `ARCHS`/`BUILD` ones above are dynamic.
