### ISSUE TITLE
How to produce Python3.12 packages in different platforms

### ISSUE THREAD

**Issue by yizhihenpidehou** [pypa/cibuildwheel#1802]
### Description

Hi, below is my GitHub Action code. However, it can only produce Python versions between 3.8- 3. 11.  How can I modify my code and produce Python3.12  packages? 

```yaml
name: Build and download wheel
on: workflow_dispatch


jobs:


    build_wheels:
      name: Build wheels on ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          # macos-13 is an intel runner, macos-14 is apple silicon
          os: [ ubuntu-latest, windows-latest, macos-13, macos-14, ubuntu-20.04]
#          python-version: [ "3.8", "3.9", "3.10","3.11", "3.12"]

      steps:
        - uses: actions/checkout@v4

        - name: Build wheels
          uses: pypa/cibuildwheel@v2.17.0

        - uses: actions/upload-artifact@v4
          with:

            python-version: ${{ matrix.python-version }}
            name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
            path: ./wheelhouse/*.whl

    build_sdist:
      name: Build source distribution
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Build sdist
          run: pipx run build --sdist

        - uses: actions/upload-artifact@v4
          with:
            name: cibw-sdist
            path: dist/*.tar.gz

    upload_pypi:
      needs: [ build_wheels, build_sdist ]
      runs-on: ubuntu-latest
      environment: pypi
      permissions:
        id-token: write
      steps:
        - uses: actions/download-artifact@v4
          with:
            # unpacks all CIBW artifacts into dist/
            pattern: cibw-*
            path: dist
            merge-multiple: true
```

### Build log

https://github.com/easy-graph/Easy-Graph/actions/workflows/buildwheel.yml

### CI config

https://github.com/easy-graph/Easy-Graph/actions/runs/8610788398/job/23596853544
