### ISSUE TITLE
Macos wheel generated/tagged for wrong macos version

### ISSUE THREAD

**Issue by LecrisUT** [pypa/cibuildwheel#1804]
### Description

For example on `macOS-13` runner it generated:
```
5 wheels produced in 8 minutes:
  spglib-2.4.0-cp310-cp310-macosx_10_9_x86_64.whl   771 kB
  spglib-2.4.0-cp311-cp311-macosx_10_9_x86_64.whl   771 kB
  spglib-2.4.0-cp312-cp312-macosx_10_9_x86_64.whl   771 kB
  spglib-2.4.0-cp38-cp38-macosx_10_9_x86_64.whl     771 kB
  spglib-2.4.0-cp39-cp39-macosx_10_9_x86_64.whl     771 kB
```

<details><summary>GH Workflow</summary>

```yaml
jobs:
  build_wheels:
    name: 🖥️ ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-11, macOS-13, macOS-14 ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        # CIBW requires emulation to build for arm linux
        # https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation
      - name: Set up QEMU for Linux-arm
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17
        env:
          CIBW_BUILD: ${{ inputs.cibw_build }}
          CIBW_ARCHS_LINUX: auto aarch64
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
```

</details>

### Build log

https://github.com/spglib/spglib/actions/runs/8647336672/job/23708827446

### CI config

https://github.com/spglib/spglib/blob/e6bdd0bafcb60ff26c7ce9ff95d13c43e56d995f/pyproject.toml#L97-L111
