### ISSUE TITLE
ModuleNotFoundError: No module named 'Cython'

### ISSUE THREAD

**Issue by YarShev** [pypa/cibuildwheel#1844]
### Description

Hi there, I am using `cibuildwheel` to build platform and python specific wheels for a project. The project has cython extensions so I have to install `Cython` beforehand to build the wheels. I specified `CIBW_BEFORE_BUILD: pip install Cython` and the wheels are built for Linux. However, I see the `ModuleNotFoundError: No module named 'Cython'` for Windows and MacOS. Am I missing on something? Here is the yml file.

```yml
name: Build and upload to PyPI

on:
  pull_request:

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout unidist
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Cython
        run: pip install Cython

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
      
      - name: Sanity check sdist files
        run: ls ./dist

  build_wheels:
    needs: build_sdist
    name: Build wheel for ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        # GitHub Actions doesn't support pairing matrix values together, let's improvise
        # https://github.com/github/feedback/discussions/7835#discussioncomment-1769026
        buildplat:
        - [ubuntu-22.04, manylinux_x86_64]
        - [ubuntu-22.04, musllinux_x86_64]
        - [macos-12, macosx_x86_64]
        # Note: M1 images on Github Actions start from macOS 14
        - [macos-14, macosx_arm64]
        - [windows-2022, win_amd64]
        - [windows-2022, win32]
        python: [["cp37", "3.7"], ["cp38", "3.8"], ["cp39", "3.9"], ["cp310", "3.10"], ["cp311", "3.11"], ["cp312", "3.12"]]

    steps:
      - name: Checkout unidist
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18.1
        env:
          CIBW_BEFORE_BUILD: pip install Cython
          CIBW_BUILD: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}
          path: ./wheelhouse/*.whl

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
```

### Build log

https://github.com/YarShev/unidist/actions/runs/9271080373/job/25505644316?pr=2

**Comment by YarShev** [comment]
Should I specify `CIBW_BUILD_FRONTEND: "pip; args: --no-build-isolation"`?

**Comment by henryiii** [comment]
If you want to avoid pyproject.toml, you can specify that, yes. If you use pyproject.toml, then you don't need the args.

**Comment by YarShev** [comment]
I'll try to the specify the option first and come back to let you know if it works.

**Comment by YarShev** [comment]
@henryiii, thanks for the suggestions! I went on with installing `wheel` and now builds for sdist and bdist passed. However, I got the correct packages of the project for linux and macos (e.g., `unidist-0.6.3-cp311-cp311-musllinux_1_2_x86_64.whl` and `unidist-0.6.3-cp310-cp310-macosx_10_9_x86_64.whl`) but not for Windows (e.g., `unidist-0+untagged.187.gbe2dd2a-cp310-cp310-win_amd64.whl`). Note that for Windows the versions is untagged and I am getting the followin error when uploading to testpypi. Here is the link to the job - https://github.com/YarShev/unidist/actions/runs/9276196183/job/25522958333.

```bash
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/          
         The use of local versions in <Version('0+untagged.187.gbe2dd2a')> is   
         not allowed. See                                                       
         https://packaging.python.org/specifications/core-metadata for more     
         information.
```

Do you know what can be wrong on my side?

**Comment by henryiii** [comment]
That's an issue with versioneer. I'd recommend using setuptools_scm instead of versioneer; just delete `versioneer.py` and all mentions of `versioneer` from your `setup.py`,  add `setuptools_scm` to your `pyproject.toml`:

```toml
[build-system]
requires = ["setuptools", "cython", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "unidist/_version.py"
```

See <https://learn.scientific-python.org/development/guides/packaging-classic>.

By the way, `build-backend = "setuptools.build_meta"` doesn't allow local imports, since it's considered an anti pattern for setup.py. You can manually add it by manipulating the path (or use `"setuptools.build_meta:__legacy__"`), but you don't need to if you switch to setuptools_scm!

If you want to continue with versioneer, I'd start by updating it. You have an old version copied into the repo, so maybe it doesn't support Windows properly? The very next version of versioneer mentions Windows fixes: https://github.com/python-versioneer/python-versioneer/blob/master/NEWS.md#release-022-07-mar-2022 (but it still doesn't seem to be very actively maintained, unlike setuptools_scm)
