### ISSUE TITLE
pp37-win_amd64 build fails due to missing `libpypy3.7-c.dll` lib on GH actions

### ISSUE THREAD

**Issue by sdimovv** [pypa/cibuildwheel#1893]
### Description

Pypy-3.7 build fails on x64 Windows GH actions runner.

As far as I can tell from the [support matrix](https://cibuildwheel.pypa.io/en/stable/#what-does-it-do) this is a supported use case.

Here is a summary my config:

* CI:

```yaml
jobs:
  ...
  build-wheels:
    name: Build wheels
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.1
        with:
          output-dir: dist
```

* `pyproject.toml`

```toml
[project]
requires-python = '>=3.7'
...

[tool.cibuildwheel]
build = "*"
free-threaded-support = false

build-frontend = "build"
build-verbosity = 1

test-command = "pytest {project}"
test-requires = [
  "pytest"
]

[build-system]
requires = [
  "meson-python>=0.16.0",
  'meson>=1.4.0',
  'ninja',
  "cffi>=1.15.1; python_version<'3.8'",
  "cffi>=1.16; python_version>='3.8'",
  "setuptools; python_version>='3.12'",
]
build-backend = 'mesonpy'
...
```

Ci fails with:

```sh
Could not find Python3 library 'C:\\Users\\runneradmin\\AppData\\Local\\pypa\\cibuildwheel\\Cache\\pypy3.7-v7.3.9-win64\\libpypy3.7-c.dll'
  Run-time dependency python found: NO (tried sysconfig)
  ..\meson.build:96:7: ERROR: Python dependency not found
 ```

This is only an issue for `Pypy-3.7` it seems. If I add `CIBW_SKIP: pp37-win*` to the action env all other builds succeed (including `Pypy-3.8+`)
