### ISSUE TITLE
Allow empty `CIBW_PLATFORM`

### ISSUE THREAD

**Issue by LecrisUT** [pypa/cibuildwheel#1965]
### Description

I was trying out `pyodide` build when I've encountered that, `CIBW_PLATFORM` is not allowed to be an empty string. This is in contrast with how `CIBW_BUILD` works where if you set it to an empty string, it uses the default ones from the config file. Here's how I was using it:
```yaml
  build_wheels:
    name: 🖥️ ${{ matrix.platform || matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-13, macOS-14 ]
        # Default do not specify platform and use the current runner's platform instead
        platform: [ "" ]
        include:
          - os: ubuntu-latest
            platform: pyodide


    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        # CIBW requires emulation to build for arm linux
        # https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation
      - name: Set up QEMU for Linux-arm
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19
        env:
          CIBW_BUILD: ${{ inputs.cibw_build }}
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_PLATFORM: ${{ matrix.platform }}
```

### Build log

https://github.com/spglib/spglib/actions/runs/10356631027/job/28667042764
