### ISSUE TITLE
pyodide build failure

### ISSUE THREAD

**Issue by LecrisUT** [pypa/cibuildwheel#1966]
### Description

Sharing my experience enabling pyodide build for `spglib`. Not sure how to debug it though.
```
  + pytest /home/runner/work/spglib/spglib/test/functional/python
  Failed to load lib  /tmp/cibw-run-2g4v63rz/cp312-pyodide_wasm32/venv-test/lib/python3.12/site-packages/spglib/_spglib.so
  Error: Didn't expect to load any more file_packager files!
      at D.u.locateFile (/home/runner/.cache/cibuildwheel/.pyodide-xbuildenv-0.26.1/0.26.1/xbuildenv/pyodide-root/dist/pyodide.js:9:10008)
      at locateFile (/home/runner/.cache/cibuildwheel/.pyodide-xbuildenv-0.26.1/0.26.1/xbuildenv/pyodide-root/dist/pyodide.asm.js:10:774)
      at loadLibData (/home/runner/.cache/cibuildwheel/.pyodide-xbuildenv-0.26.1/0.26.1/xbuildenv/pyodide-root/dist/pyodide.asm.js:10:153821)
      at getExports (/home/runner/.cache/cibuildwheel/.pyodide-xbuildenv-0.26.1/0.26.1/xbuildenv/pyodide-root/dist/pyodide.asm.js:10:154250)
      at loadDynamicLibrary (/home/runner/.cache/cibuildwheel/.pyodide-xbuildenv-0.26.1/0.26.1/xbuildenv/pyodide-root/dist/pyodide.asm.js:10:154598)
      at /home/runner/.cache/cibuildwheel/.pyodide-xbuildenv-0.26.1/0.26.1/xbuildenv/pyodide-root/dist/pyodide.asm.js:10:151157
```

### Build log

https://github.com/spglib/spglib/actions/runs/10356874250/job/28667846634

**Comment by henryiii** [comment]
```
PermissionError: [Errno 2] Permission denied: '/home/runner/work/spglib/spglib/pytest-cache-files-sodvmnvb/README.md'
```

You need to turn off the pytest cache for Pyodide or just ignore the warning if you have warnings as errors.

I often have this, too:

```toml
[tool.pytest.ini_options]
filterwarnings = [
  "error",
  "default:could not create cache path:pytest.PytestCacheWarning",
]

[[tool.cibuildwheel.overrides]]
select = "*pyodide*"
inherit.environment = "append"
environment.CFLAGS = "-fexceptions"
environment.LDFLAGS = "-fexceptions"
build-frontend = {name = "build", args = ["--exports", "whole_archive"]}
```

(Next release of pybind11 might stop requiring the `-fexceptions` to be added. Other frameworks may or may not need it.)
