### ISSUE TITLE
ubuntu-latest stuck when building wheels of manylinux2014_aarch64

### ISSUE THREAD

**Issue by TrueRou** [pypa/cibuildwheel#2114]
### Description

All the other Windows, macOS, Linux builds work fine until on linux aarch64, the action job stuck here for a long period of time doing nothing.

It seems like `Error response from daemon: No such image: quay.io/pypa/manylinux2014_aarch64:2024.11.16-1` is a false positive, since the docker is pulled as expected.

`exec /usr/local/bin/manylinux-entrypoint: exec format error` is what the problem is I think.
```
Starting container image quay.io/pypa/manylinux2014_aarch64:2024.11.16-1...
  info: This container will host the build for cp39-manylinux_aarch64, cp310-manylinux_aarch64, cp311-manylinux_aarch64, cp312-manylinux_aarch64, cp313-manylinux_aarch64...
  + docker version -f '{{json .}}'
  + docker image inspect quay.io/pypa/manylinux2014_aarch64:2024.11.16-1 --format '{{.Os}}/{{.Architecture}}'
  Error response from daemon: No such image: quay.io/pypa/manylinux2014_aarch64:2024.11.16-1
  2024.11.16-1: Pulling from pypa/manylinux2014_aarch64
  fc035e9644c2: Pulling fs layer
  <omit docker pulling layers>
  06b0a7928a87: Pull complete
  Digest: sha256:c1cb9f94cfa942da518bfc68de177cf06f69de217a38e53f479ea786bdaa07c1
  Status: Downloaded newer image for quay.io/pypa/manylinux2014_aarch64:2024.11.16-1
  792b3b2a59221b2c742dc45e59de00f0e3e354414070ecf1229acb1490ee9c74
      + /bin/true
  exec /usr/local/bin/manylinux-entrypoint: exec format error
```

### Build log

https://gist.github.com/TrueRou/033fd58290b9bd93b6debc75f282668f

### CI config

https://gist.github.com/TrueRou/0ec30144429bc3b10da127935f00d2d6

### pyproject.toml

```toml
[tool.cibuildwheel]
before-build = "pip install -r requirements.txt"
skip = "cp36-* cp37-* cp38-* pp*"

[build-system]
requires = ["setuptools", "Cython"]

build-backend = "setuptools.build_meta"
```

### requirements.txt

```
cython>=3.0.11
setuptools>=75.4.0
httpx>=0.28.1
cibuildwheel>=2.22.0
cryptography>=38.0
```
