### ISSUE TITLE
Random segfault for QEMU builds in GitHub Actions

### ISSUE THREAD

**Issue by Rot127** [pypa/cibuildwheel#2257]
### Description

This is not so much an issue of `cibuildwheel` (I think), except you should be aware of it.

GCC builds segfault on the AArch64 musllinux 1.2, manylinux 2014 and manylinux 2.28.

I couldn't pin-point a possible GCC issue to it. But it is odd that it appears in a stable version.
Maybe: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=118583
Haven't tested it yet though.

Feel free to close this if you see it as out of scope. But I wanted to drop it here in case people search for it in this context. Or others already found a solution.

Runs:

`manylinux 2.28`
https://github.com/capstone-engine/capstone/actions/runs/13012237284/job/36292511727?pr=2614

`manylinux 2014`
https://github.com/capstone-engine/capstone/actions/runs/13011576391/job/36290786445?pr=2614

`musllinux 1.2`
https://github.com/capstone-engine/capstone/actions/runs/13011576391/job/36290786852?pr=2614

**Comment by henryiii** [comment]
It's a bug in emulation. You can either pin the QEMU version, or better yet, use `ubuntu-24.04-arm` or `ubuntu-22.04-arm` instead of emulation, which is ~10x faster too.

See https://github.com/pypa/cibuildwheel/discussions/2256. I'll copy @joerick's answer here for posterity:

I believe you're hitting a bug around setup-qemu-action. I didn't see it myself but @mayeut just pushed this fix to our repo-

https://github.com/pypa/cibuildwheel/pull/2253/commits/4538497e648c6856ad8ae129e7871c6bace7ce07

The referenced issues are https://github.com/docker/setup-qemu-action/issues/188 and https://github.com/tonistiigi/binfmt/issues/215. @mayeut's workaround is the following in a github workflow:

```yaml
    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v3
      with:
        # This should be temporary
        # xref https://github.com/docker/setup-qemu-action/issues/188
        # xref https://github.com/tonistiigi/binfmt/issues/215
        image: tonistiigi/binfmt:qemu-v8.1.5
```
