### ISSUE TITLE
delocate-wheel is missing arch x86_64 on arm macos-14 in py 3.13 build

### ISSUE THREAD

**Issue by pechersky** [pypa/cibuildwheel#2345]
### Description

I am building py 3.13 wheels for https://github.com/rdkit/rdkit. This did not work on delocate 0.12.0 due to "This function does not support separate values per-architecture", as described [in an issue](https://github.com/matthew-brett/delocate/issues/153). The 0.13.0 release, which is a dependency of cibuildwheel 2.23, has better support for per-architecture values.

However, I now get a new error at the `delocate-wheel` step, included below. I do not get this error on py3.12 macos arm builds or earlier.

My build commands are
```
python -m pip install cibuildwheel==2.23.2
python -m cibuildwheel --output-dir wheelhouse
```

My build env is
```
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
          CIBW_ARCHS: all
          # `SYSTEM_VERSION_COMPAT=0` due to https://github.com/pypa/cibuildwheel/issues/1767
          CIBW_ENVIRONMENT: MACOSX_DEPLOYMENT_TARGET=${{ matrix.target }} ${{ matrix.python == 38 && 'SYSTEM_VERSION_COMPAT=0' || ''}}
```

My matrix for the affected runner is
```
          - os: macos-14
            python: 313
            platform_id: macosx_arm64
            target: "14.0"
```

The top part of the error traceback is below
```
Traceback (most recent call last):
  File "/private/var/folders/qn/7t0vq3ts721cmgt0tgrtgzl80000gn/T/cibw-run-cdsnb5b9/cp313-macosx_arm64/build/venv/bin/delocate-wheel", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/private/var/folders/qn/7t0vq3ts721cmgt0tgrtgzl80000gn/T/cibw-run-cdsnb5b9/cp313-macosx_arm64/build/venv/lib/python3.13/site-packages/delocate/cmd/delocate_wheel.py", line 115, in main
    copied = delocate_wheel(
        wheel,
    ...<4 lines>...
        **delocate_values(args),
    )
  File "/private/var/folders/qn/7t0vq3ts721cmgt0tgrtgzl80000gn/T/cibw-run-cdsnb5b9/cp313-macosx_arm64/build/venv/lib/python3.13/site-packages/delocate/delocating.py", line 1094, in delocate_wheel
    raise DelocationError(
    ...<2 lines>...
    )
delocate.libsana.DelocationError: Some missing architectures in wheel
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_atomic.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_charconv.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_chrono.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_container.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_context.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_contract.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_coroutine.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_date_time.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_fiber.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_fiber_numa.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_filesystem.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_graph.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_iostreams.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_json.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_locale.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_log.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_log_setup.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_math_c99.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_math_c99f.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_math_c99l.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_math_tr1.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_math_tr1f.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_math_tr1l.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_nowide.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_numpy313.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_prg_exec_monitor.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_program_options.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_python313.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_random.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_regex.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_serialization.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_thread.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_timer.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_type_erasure.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_unit_test_framework.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_url.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_wave.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/boost61a11d964b046/p/lib/libboost_wserialization.dylib
/usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /usr/local/lib/libRDKitRDGeneral.1.dylib
[...]
```

**Comment by pechersky** [comment]
Perhaps related, during build, there are `ld` warnings like:
```
  ld: warning: ignoring file '/Users/runner/.conan2/p/b/zliba6bbef6d56475/p/lib/libz.a[2](adler32.c.o)': found architecture 'arm64', required architecture 'x86_64'
```

**Comment by henryiii** [comment]
Are you using libraries from brew?  You can't use libraries that you did not compile for cross-compilation. Libraries such as those from brew were not prepared for cross-compilation. Either you need to compile them yourself or you need to build Intel on macOS-13 and Apple Silicon on macOS-14. You really shouldn't be using anything from brew, though, it's explicitly unsupported to distribute these, they aren't compiled for older macOS's either, for example.

**Comment by pechersky** [comment]
No, not installing anything via brew (I've been bitten by that before). Does `actions/setup-python` count?

The whole workflow for macs is

```
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.11'
      - name: Create /usr/local/lib for macs
        if: ${{ matrix.platform_id == 'macosx_arm64' }}
        run: |
          sudo mkdir -p /usr/local/lib && sudo chmod 0777 /usr/local/lib
      - name: Build wheels
        env:
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
          CIBW_ARCHS: all
          # `SYSTEM_VERSION_COMPAT=0` due to https://github.com/pypa/cibuildwheel/issues/1767
          CIBW_ENVIRONMENT: MACOSX_DEPLOYMENT_TARGET=${{ matrix.target }} ${{ matrix.python == 38 && 'SYSTEM_VERSION_COMPAT=0' || ''}}
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: "cp {wheel} {dest_dir}"

        run: |
          python -m pip install cibuildwheel==2.23.2
          python -m cibuildwheel --output-dir wheelhouse
        shell: bash
```

**Comment by pechersky** [comment]
Hmm, could the `CIBW_ARCHS: all` be the issue?

**Comment by henryiii** [comment]
Ah, I see `conan` in the path, I guess Conan is pulling a pre-built lib?

`CIBW_ARCHS: all` is why it's trying to build both. In fact, that might even try to build universal at the same time - it's probably better not to set that.

**Comment by Czaki** [comment]
> Hmm, could the `CIBW_ARCHS: all` be the issue?

Yes. It requires for you to have all dependencies built for both architectures. 

As intel runners are still available, I suggest building x86_64 on intel runner.

**Comment by pechersky** [comment]
I hope to update soon on this, but `x.org` seems down, so conan is failing when trying to install `pixman`.

**Comment by pechersky** [comment]
I tried setting CIBW_ARCHS_MACOS to `arm64` but still have the issue on 3.13. Here's the cibuildwheel config in the CI run
```
cibuildwheel version 2.23.2

Build options:
  platform: macos
  allow_empty: False
  architectures: arm64    <---- note here
  build_selector: 
    build_config: cp313-macosx_arm64
    skip_config: 
    requires_python: None
    enable: ['pypy']
  output_dir: /Users/runner/work/rdkit-pypi/rdkit-pypi/wheelhouse
  package_dir: /Users/runner/work/rdkit-pypi/rdkit-pypi
  test_selector: 
    skip_config:
  before_all: brew install gnu-sed
  before_build: 
  before_test: 
  build_frontend: None
  build_verbosity: 1
  config_settings: 
  container_engine: docker
  dependency_constraints: pinned
  environment: 
    MACOSX_DEPLOYMENT_TARGET=14.0
  manylinux_images: None
  musllinux_images: None
  repair_command: export DYLD_LIBRARY_PATH='/usr/local/lib:/usr/lib' && source conan/conanrun.sh && delocate-listdeps {wheel} && delocate-wheel --require-archs arm64 -w {dest_dir} {wheel}  <---- note here also
  test_command: pytest --exitfirst --verbose --failed-first {package}/tests
  test_extras: 
  test_groups: 
  test_requires: 
    pytest
```

The wheel built, and in the repair build starts with
```
Repairing wheel...
  
  + export DYLD_LIBRARY_PATH='/usr/local/lib:/usr/lib' && source conan/conanrun.sh && delocate-listdeps /private/var/folders/r1/4882c7yd7wx9hcpc__xp04_m0000gn/T/cibw-run-6u8uqi3c/cp313-macosx_arm64/built_wheel/rdkit-2025.3.1.post1-cp313-cp313-macosx_14_0_arm64.whl && delocate-wheel --require-archs arm64 -w /private/var/folders/r1/4882c7yd7wx9hcpc__xp04_m0000gn/T/cibw-run-6u8uqi3c/cp313-macosx_arm64/repaired_wheel /private/var/folders/r1/4882c7yd7wx9hcpc__xp04_m0000gn/T/cibw-run-6u8uqi3c/cp313-macosx_arm64/built_wheel/rdkit-2025.3.1.post1-cp313-cp313-macosx_14_0_arm64.whl
```
and hits the DelocationError
```
Traceback (most recent call last):
    File "/private/var/folders/r1/4882c7yd7wx9hcpc__xp04_m0000gn/T/cibw-run-6u8uqi3c/cp313-macosx_arm64/build/venv/bin/delocate-wheel", line 8, in <module>
      sys.exit(main())
               ~~~~^^
    File "/private/var/folders/r1/4882c7yd7wx9hcpc__xp04_m0000gn/T/cibw-run-6u8uqi3c/cp313-macosx_arm64/build/venv/lib/python3.13/site-packages/delocate/cmd/delocate_wheel.py", line 115, in main
      copied = delocate_wheel(
          wheel,
      ...<4 lines>...
          **delocate_values(args),
      )
    File "/private/var/folders/r1/4882c7yd7wx9hcpc__xp04_m0000gn/T/cibw-run-6u8uqi3c/cp313-macosx_arm64/build/venv/lib/python3.13/site-packages/delocate/delocating.py", line 1094, in delocate_wheel
      raise DelocationError(
      ...<2 lines>...
      )
  delocate.libsana.DelocationError: Some missing architectures in wheel
  /usr/local/lib/libRDKitRDBoost.1.dylib needs arch x86_64 missing from /Users/runner/.conan2/p/b/booste01e6478ef53a/p/lib/libboost_atomic.dylib
```
