### ISSUE TITLE
Case sensitivity of CIBW_ARCHS for Windows on ARM64

### ISSUE THREAD

**Issue by hugovk** [pypa/cibuildwheel#2373]
### Description

With:

* `uses: pypa/cibuildwheel@v2.23.2`
* `runs-on: windows-11-arm`
* `CIBW_ARCHS: "arm64"

https://github.com/ultrajson/ultrajson/pull/663/commits/f60b4f665b717ecb6fd8272cad25aa5a7e2ff170

We got an error:

```
cibuildwheel: Invalid archs option {<Architecture.arm64: 'arm64'>}. Windows only supports [<Architecture.AMD64: 'AMD64'>, <Architecture.ARM64: 'ARM64'>, <Architecture.x86: 'x86'>] at the moment. If you want to set emulation architectures on Linux, use CIBW_ARCHS_LINUX instead.
  architectures: arm64
  build_selector: 
    build_config: *
    skip_config: pp39*
    requires_python: >=3.9
    enable: ['cpython-prerelease', 'pypy']
```

Changing it to uppercase fixed it:

```diff
-CIBW_ARCHS: "arm64"
+CIBW_ARCHS: "ARM64"
```

https://github.com/ultrajson/ultrajson/actions/runs/14591266684/job/40927895459?pr=663
https://github.com/ultrajson/ultrajson/actions/runs/14591266684/workflow?pr=663

The docs at https://cibuildwheel.pypa.io/en/stable/options/#archs do indeed show uppercase "ARM64" for Windows and lowercase "arm64" for macOS, but don't mention if they are case-sensitive.

* If they are case sensitive, and it makes sense for them to remain so, please close this.

* If they are case sensitive, but they don't need to be, this is a feature request.

* If they are not meant to be case sensitive, this is a bug report.

I was a little surprised by the case sensitivity, and misread the error as Windows on ARM64 being unavailable for PyPy (which as it happens is true, but not what's being reported here).

Allowing either case will remove a little paper cut and help avoid confusion as others add support for Windows on ARM64.

Thank you!

### Build log

https://github.com/ultrajson/ultrajson/actions/runs/14590225899/job/40925835572?pr=663

### CI config

https://github.com/ultrajson/ultrajson/actions/runs/14590225899/workflow?pr=663
