### ISSUE TITLE
manylinux-pypy settings?

### ISSUE THREAD

**Issue by henryiii** [pypa/cibuildwheel#711]
> Rework (at least discuss) `CIBW_MANYLINUX_PYPY_*` options as mentioned in https://github.com/pypa/cibuildwheel/pull/671#discussion_r637931737 and https://github.com/pypa/cibuildwheel/pull/671#issuecomment-847348461 before 2

Currently, we have two separately defined images; pypy and non-pypy. Setting one does not affect the other. So, for example:

```toml
[tool.cibuildwheel]
manylinux-x86_64_image = "manylinux2014"
manylinux-i686-image = "manylinux2014"
# Still default
#  manylinux-pypy_x86_64-image = "manylinux2010"
#  manylinux-pypy_i686-image = "manylinux2010"
```

Since the manylinux images come by default with pypy now, we should consider if we want to change the behavior in 2.0. Our options:

1. Drop pypy variants; they just use the same thing as CPython. Makes it harder to statically define these, though - for example, setting manylinux1 will make it really hard to also build for PyPy. Not fond of this option.
2. Default to the regular value if undefined, but take the "override" if given. So that would make the pypy wheels 2014 in the example above, but you could still override pypy separately.
3. Keep the current behavior.

If we were designing from scratch, I'd probably go with 2. But don't think it's important enough to cause issues over? Especially since manylinux1 is is still very common (over 50% of our users), and setting manylinux1 for pypy is a mistake.
