### ISSUE TITLE
macOS: wheels names disregarding deployment target for cp38+

### ISSUE THREAD

**Issue by boschmitt** [pypa/cibuildwheel#818]
I have a Github workflow that builds wheels for macOS. Since my library depends on C++17 for both core language features and library features, I set `MACOSX_DEPLOYMENT_TARGET` to be fairly high, i.e., `10.15`.

When building the wheels, I get wheels with the correct name for CPython versions `3.6` and `3.7`. However, the other versions are named `*10.9*`:

```
5 wheels produced in 30 minutes:
  tweedledum-1.1.1-cp310-cp310-macosx_10_9_x86_64.whl
  tweedledum-1.1.1-cp36-cp36m-macosx_10_15_x86_64.whl
  tweedledum-1.1.1-cp37-cp37m-macosx_10_15_x86_64.whl
  tweedledum-1.1.1-cp38-cp38-macosx_10_9_x86_64.whl
  tweedledum-1.1.1-cp39-cp39-macosx_10_9_x86_64.whl
```

I believe the culprit code is:

https://github.com/pypa/cibuildwheel/blob/2709a49715535c71a85aed5b5dedde28fb0685e0/cibuildwheel/macos.py#L286-L290

As a workaround, I have manually set `_PYTHON_HOST_PLATFORM` to be `macosx-10.15-x86_64`, but I'm not sure if there might be other implications.

**Comment by henryiii** [comment]
I feel like this was a bug that we were going to fix, but seems to have not been fixed. It should be fixed, or we should use https://github.com/pypa/wheel/issues/407 which I haven't had a chance to implement yet.

**Comment by joerick** [comment]
Agreed, this looks like a bug to me. I think that we should be setting `_PYTHON_HOST_PLATFORM` to the maximum of our known-good values for the arch and the user supplied MACOSX_DEPLOYMENT_TARGET. In fact, we already have something like that implemented in the tests...

https://github.com/pypa/cibuildwheel/blob/02652e662e1c88a20821273926b76150e3441531/test/utils.py#L89-L99

So I think we should bring the same logic into the code, too. 

Do you have any opinion on this @mayeut? I seem to remember discussing `_PYTHON_HOST_PLATFORM` and `MACOSX_DEPLOYMENT_TARGET`, and I think you added the original `_PYTHON_HOST_PLATFORM` override a few years back. Was there a particular reason that it was static and not tied to `MACOSX_DEPLOYMENT_TARGET`?

**Comment by henryiii** [comment]
Please see https://github.com/pypa/cibuildwheel/pull/819 :)

**Comment by joerick** [comment]
I'm working through my emails and I now see #819 with a @mayeut review! :)

**Comment by joerick** [comment]
@boschmitt would you mind taking a look at #820? I'm having trouble recreating this bug.

**Comment by boschmitt** [comment]
@joerick I had a look at #820, but I couldn't figure it out why the errors is not happening. 

First, I thought that it was because I'm using `cibuildwheel@v2.1.1` (sorry I failed to mention it before) and that branch might be using newer (unreleased) code. So I run my workflow again using `cibuildwheel@main`:

I tried to simplify the workflow as much as possible: Here is the [result](https://github.com/boschmitt/tweedledum/runs/3559795435)

The relevant parts:
```
Run pypa/cibuildwheel@main
  with:
    package-dir: .
    output-dir: wheelhouse
  env:
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.8.11/x64
    CIBW_BUILD: cp36-macosx_x86_64 cp39-macosx_x86_64
    CIBW_ARCHS: x86_64
    CIBW_TEST_REQUIRES: pytest
    CIBW_TEST_COMMAND: pytest --import-mode importlib -v {project}/python/test/
    CMAKE_BUILD_PARALLEL_LEVEL: 2
    MACOSX_DEPLOYMENT_TARGET: 10.15
```

Produced wheels:
```
2 wheels produced in 18 minutes:
  tweedledum-1.1.0-cp36-cp36m-macosx_10_15_x86_64.whl
  tweedledum-1.1.0-cp39-cp39-macosx_10_9_x86_64.whl
```

I'm doing some others tests on my side and I will try to look a bit further on #820.
