### ISSUE TITLE
Conditional architecture settings

### ISSUE THREAD

**Issue by JesseFarebro** [pypa/cibuildwheel#849]
### Description

Hi! I just want to start off by saying thank you for the amazing tool, `cibuildwheel` has been integral in releasing simulators for AI workloads, in particular [The Arcade Learning Environment](https://github.com/mgbellemare/Arcade-Learning-Environment).

I want to switch our project over to using `pyproject.toml` and I really wish I could set settings based on the architecture. In our case, we have to install dependencies from vcpkg and this does depend on the architecture. For example, we currently have our Github Actions CI config matrix like:

```yml
strategy:
      matrix:
        include:
          - config: {"name": "Linux", "os": "ubuntu-latest", "arch": "x86_64", "triplet": "x64-linux-mixed"}
          - config: {"name": "Windows", "os": "windows-latest", "arch": "AMD64", "triplet": "x64-windows"}
          - config: {"name": "macOS", "os": "macos-latest", "arch": "x86_64", "triplet": "x64-osx-mixed"}
          - config: {"name": "macOS", "os": "macos-latest", "arch": "arm64", "triplet": "arm64-osx-mixed"}
```

We hardcode the specific triplet (build config) but I really wish I didn't have to specify this in Github Actions and I could have something like:

```toml

[tool.cibuildwheel.macos.arm64]
environment = { VCPKG_DEFAULT_TRIPLET = "arm64-osx-mixed" }
```

Is there a better way to achieve what I'm looking for here? Would this be something that would be worth supporting?

### CI config

https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/.github/workflows/build-ale-py.yml
