### ISSUE TITLE
Doc Bug: wrong syntax in pyproject.toml example for CIBW_TEST_EXTRAS

### ISSUE THREAD

**Issue by MuellerSeb** [pypa/cibuildwheel#863]
### Description

Hey there,
found a wrong syntax in pyproject.toml example for CIBW_TEST_EXTRAS:
https://cibuildwheel.readthedocs.io/en/stable/options/#examples_14

Should be:
```toml
[tool.cibuildwheel]
# Will cause the wheel to be installed with `pip install <wheel_file>[test,qt]`
test-extras = ["test", "qt"]
```
`=` instead of `:`.
