### ISSUE TITLE
MacOS producing wheel for 10.9 even though 11.0 is specified

### ISSUE THREAD

**Issue by tonybaloney** [pypa/cibuildwheel#952]
### Description

I'm trying to produce universal2, x64 and arm64 wheels for macOS 11+.

The extension module specifically requires 11.0+ and would fail in older versions of Mac. 

I've tried setting `MACOSX_DEPLOYMENT_TARGET=11.0` after looking at the source code. There's nothing in the documentation how to change the deployment target for the wheels to be 11.0 instead of 10.9

In spite of this, CI produces the file -

`pyjion-1.2.0-cp310-cp310-macosx_10_9_universal2.whl`

The build workflow is -

```yaml
name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.2.2
        env:
          CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
          CIBW_BEFORE_BUILD_MACOS: "bash eng/install-dotnet.sh --version 6.0.100"
          CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=11.0

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
```

pyproject.toml

```toml
[build-system]
requires = ["setuptools", "wheel", "scikit-build", "cmake", "ninja"]

[tool.cibuildwheel.macos]
before-build = "bash eng/install-dotnet.sh --version 6.0.100"
environment = {MACOSX_DEPLOYMENT_TARGET=11.0}
repair-wheel-command = ""
archs = ["x86_64", "universal2"]
```
